### Downloading PDFs

In [225]:
from selenium.webdriver.chrome.options import Options
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
import time
import os
import requests
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC

BASE_DIR = os.path.join("/Users/aryankhurana/Electricity-Forecasting-Indian-States")
DOWNLOAD_DIR = os.path.join(BASE_DIR, "artifacts", "downloaded_pdfs")

URL = "https://grid-india.in/en/reports/weekly-report"

# Ensure download directory exists
os.makedirs(DOWNLOAD_DIR, exist_ok=True)

# === Setup Selenium with Brave ===
options = Options()
options.binary_location = "C:\\Program Files\\BraveSoftware\\Brave-Browser\\Application\\brave.exe"
service = Service(executable_path=r"/Users/aryankhurana/Downloads/Softwares/chromedriver-mac-arm64/chromedriver")
driver = webdriver.Chrome(service=service, options=options)

driver.get(URL)
wait = WebDriverWait(driver, 10)

# === STEP 1: Select "ALL" from dropdown ===
try:
    dropdown_control = wait.until(EC.element_to_be_clickable(
        (By.CSS_SELECTOR, "div.my-select__control")
    ))
    dropdown_control.click()
    time.sleep(1)

    # Wait for dropdown menu to appear
    wait.until(EC.presence_of_element_located(
        (By.CSS_SELECTOR, "div[class*='my-select__menu']")
    ))

    # Find and click ALL option
    all_option = wait.until(EC.element_to_be_clickable(
        (By.XPATH, "//div[contains(@class, 'my-select__option') and text()='ALL']")
    ))
    all_option.click()
    time.sleep(2)

    print("Selected ALL option")
    
except Exception as e:
    print("Dropdown selection failed:", e)
    driver.quit()
    exit()

# === STEP 2: Scrape PDF links with pagination ===
all_pdf_links = set()
page_number = 1

while True:
    print(f"Scraping Page {page_number}...")
    time.sleep(2)

    try:
        # Wait for PDF links to load
        wait.until(EC.presence_of_all_elements_located((By.XPATH, "//a[contains(@href, '.pdf')]")))

        pdf_links = driver.find_elements(By.XPATH, "//a[contains(@href, '.pdf')]")
        for link in pdf_links:
            driver.execute_script("window.scrollBy(0, 52);")
            time.sleep(1)

            href = link.get_attribute("href")
            if href and href.endswith(".pdf"):
                all_pdf_links.add(href)

        try:
            next_button = driver.find_element(By.XPATH, "//button[@aria-label='Next Page']")
            if next_button.get_attribute("disabled") is not None:
                print("Reached the last page.")
                break
            next_button.click()
            time.sleep(2)
            page_number += 1
        except Exception as e:
            print("Error navigating to next page:", e)
            break
        # Scroll to the very top of the page
        driver.execute_script("window.scrollTo(0, 100);")
        time.sleep(1)

    except Exception as e:
        print("Error during pagination:", e)
        break
driver.quit()
try:
    print(f"Total PDFs found: {len(all_pdf_links)}. Downloading...")
    for i, link in enumerate(all_pdf_links, 1):
        filename = os.path.join(DOWNLOAD_DIR, f"report_{i:03d}.pdf")
        try:
            response = requests.get(link)
            with open(filename, "wb") as f:
                f.write(response.content)
            print(f"Downloaded: {filename}")
        except Exception as e:
            print(f"Failed to download {link}: {e}")

    print("✅ All downloads complete.")
except Exception as e:
    print(f"Error during download: {e}")

SessionNotCreatedException: Message: session not created
from unknown error: no chrome binary at C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#sessionnotcreatedexception
Stacktrace:
0   chromedriver                        0x0000000105017570 cxxbridge1$str$ptr + 2731064
1   chromedriver                        0x000000010500f468 cxxbridge1$str$ptr + 2698032
2   chromedriver                        0x0000000104b5e3f8 cxxbridge1$string$len + 90664
3   chromedriver                        0x0000000104b8f6c4 cxxbridge1$string$len + 292084
4   chromedriver                        0x0000000104b8e7d8 cxxbridge1$string$len + 288264
5   chromedriver                        0x0000000104bd2d3c cxxbridge1$string$len + 568172
6   chromedriver                        0x0000000104bd25f0 cxxbridge1$string$len + 566304
7   chromedriver                        0x0000000104b99a0c cxxbridge1$string$len + 333884
8   chromedriver                        0x0000000104fda5f4 cxxbridge1$str$ptr + 2481340
9   chromedriver                        0x0000000104fdd85c cxxbridge1$str$ptr + 2494244
10  chromedriver                        0x0000000104fbb248 cxxbridge1$str$ptr + 2353424
11  chromedriver                        0x0000000104fde118 cxxbridge1$str$ptr + 2496480
12  chromedriver                        0x0000000104fac2f8 cxxbridge1$str$ptr + 2292160
13  chromedriver                        0x0000000104ffe00c cxxbridge1$str$ptr + 2627284
14  chromedriver                        0x0000000104ffe198 cxxbridge1$str$ptr + 2627680
15  chromedriver                        0x000000010500f0a4 cxxbridge1$str$ptr + 2697068
16  libsystem_pthread.dylib             0x00000001882aec0c _pthread_start + 136
17  libsystem_pthread.dylib             0x00000001882a9b80 thread_start + 8

### Extracting Tables from PDFs

In [ ]:
import os

In [ ]:
BASE_DIR = os.path.join("/Users/aryankhurana/Electricity-Forecasting-Indian-States")
DOWNLOAD_DIR = os.path.join(BASE_DIR, "artifacts", "downloaded_pdfs")

In [ ]:
import tabula
import PyPDF2
import pandas as pd

# Folder paths
pdf_dir = os.path.join(BASE_DIR, "artifacts", "downloaded_pdfs")
csv_dir = os.path.join(BASE_DIR, "artifacts", "downloaded_csvs")

os.makedirs(csv_dir, exist_ok=True)

# List all PDF files in the directory
pdf_files = [os.path.join(pdf_dir, f) for f in os.listdir(pdf_dir) if f.endswith(".pdf")]

# Process each PDF
for idx, file_path in enumerate(pdf_files, 1):
    try:
        print(f"Processing {file_path}...")

        with open(file_path, 'rb') as f:
            reader = PyPDF2.PdfReader(f)
            page_found = False

            for i in range(1, len(reader.pages)):
                text = reader.pages[i].extract_text()
                if text and 'Energy Consumption in States (MUs)' in text:
                    page_found = True
                    required_page = i + 1  # tabula is 1-based
                    break

        if not page_found:
            print(f"❌ Table not found in {file_path}")
            continue

        # Extract table from the page using tabula
        tables = tabula.read_pdf(file_path, pages=required_page, multiple_tables=True)

        if tables:
            df = tables[0]
            # Drop the last row if it is total or NaN
            df = df.dropna(how='all')
            if 'ALL INDIA TOTAL' in df.iloc[-1].astype(str).values:
                df = df.iloc[:-1]

            csv_filename = os.path.splitext(os.path.basename(file_path))[0] + ".csv"
            csv_path = os.path.join(csv_dir, csv_filename)
            df.to_csv(csv_path, index=False)
            print(f"✅ Saved to: {csv_path}")
        else:
            print(f"⚠️ No tables extracted from page {required_page} in {file_path}")

    except Exception as e:
        print(f"❌ Error processing {file_path}: {e}")

Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_253.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_253.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_247.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_247.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_290.pdf...
❌ Error processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_290.pdf: EOF marker not found
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_284.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_284.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_079.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_079.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_051.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_051.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_045.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_045.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_092.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_092.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_086.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_086.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_119.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_119.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_125.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_125.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_131.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_131.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_441.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_441.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_327.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_327.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_333.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_333.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_455.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_455.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_332.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_332.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_454.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_454.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_440.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_440.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_326.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_326.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_130.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_130.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_124.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_124.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_118.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_118.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_087.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_087.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_093.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_093.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_044.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_044.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_050.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_050.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_078.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_078.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_285.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_285.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_291.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_291.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_246.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_246.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_252.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_252.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_278.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_278.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_244.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_244.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_250.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_250.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_287.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_287.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_293.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_293.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_046.pdf...
❌ Error processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_046.pdf: EOF marker not found
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_052.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_052.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_085.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_085.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_091.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_091.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_132.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_132.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_126.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_126.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_318.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_318.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_456.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_456.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_330.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_330.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_324.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_324.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_442.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_442.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_325.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_325.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_443.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_443.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_331.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_331.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_319.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_319.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_127.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_127.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_133.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_133.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_090.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_090.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_084.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_084.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_053.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_053.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_047.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_047.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_292.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_292.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_286.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_286.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_251.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_251.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_245.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_245.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_279.pdf...

Got stderr: Jul 24, 2025 12:58:30 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+207 (207) in font ICJJJA+Mangal-Bold
Jul 24, 2025 12:58:30 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+232 (232) in font ICJJJA+Mangal-Bold
Jul 24, 2025 12:58:30 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+227 (227) in font ICJJJA+Mangal-Bold
Jul 24, 2025 12:58:30 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+419 (419) in font ICJJJA+Mangal-Bold
Jul 24, 2025 12:58:30 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+224 (224) in font ICJJJA+Mangal-Bold
Jul 24, 2025 12:58:30 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+230 (230) in font ICJJJA+Mangal-Bold
Jul 24, 2025 12:58:30 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+218 (218) in font ICJJJA+Mangal-Bold
Jul 24, 2025 12:58:30 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+231 (231) in font ICJJJA+Mangal-Bold
Jul 24, 2025 12:58:30 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+219 (219) in font ICJJJA+Mangal-Bold
Jul 24, 2025 12:58:30 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+509 (509) in font ICJJJA+Mangal-Bold
Jul 24, 2025 12:58:30 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+583 (583) in font ICJJJA+Mangal-Bold
Jul 24, 2025 12:58:30 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+585 (585) in font ICJJJA+Mangal-Bold
Jul 24, 2025 12:58:30 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+581 (581) in font ICJJJA+Mangal-Bold
Jul 24, 2025 12:58:30 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+618 (618) in font ICJJJA+Mangal-Bold

✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_279.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_241.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_241.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_255.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_255.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_269.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_269.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_282.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_282.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_296.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_296.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_043.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_043.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_057.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_057.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_080.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_080.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_094.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_094.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_137.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_137.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_123.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_123.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_335.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_335.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_453.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_453.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_447.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_447.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_321.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_321.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_309.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_309.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_308.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_308.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_446.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_446.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_320.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_320.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_334.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_334.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_452.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_452.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_122.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_122.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_136.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_136.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_095.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_095.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_081.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_081.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_056.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_056.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_042.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_042.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_297.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_297.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_283.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_283.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_268.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_268.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_254.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_254.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_240.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_240.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_256.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_256.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_242.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_242.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_295.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_295.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_281.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_281.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_054.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_054.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_040.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_040.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_068.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_068.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_097.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_097.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_083.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_083.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_120.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_120.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_134.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_134.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_108.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_108.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_322.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_322.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_444.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_444.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_450.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_450.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_336.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_336.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_451.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_451.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_337.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_337.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_323.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_323.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_445.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_445.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_109.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_109.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_135.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_135.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_121.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_121.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_082.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_082.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_096.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_096.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_069.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_069.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_041.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_041.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_055.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_055.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_280.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_280.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_294.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_294.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_243.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_243.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_257.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_257.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_218.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_218.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_230.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_230.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_224.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_224.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_032.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_032.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_026.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_026.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_146.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_146.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_152.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_152.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_185.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_185.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_191.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_191.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_378.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_378.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_344.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_344.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_422.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_422.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_436.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_436.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_350.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_350.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_387.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_387.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_393.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_393.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_392.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_392.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_386.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_386.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_437.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_437.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_351.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_351.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_345.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_345.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_423.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_423.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_379.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_379.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_190.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_190.csv

Got stderr: Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+162 (162) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+287 (287) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+207 (207) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+464 (464) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+232 (232) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+465 (465) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+227 (227) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+547 (547) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+419 (419) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+292 (292) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+224 (224) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+230 (230) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+218 (218) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+231 (231) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+282 (282) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+290 (290) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+91 (91) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+871 (871) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+219 (219) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+466 (466) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+875 (875) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+200 (200) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+509 (509) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+872 (872) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+583 (583) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+585 (585) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+581 (581) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+467 (467) in font CIDFont+F2
Jul 24, 2025 12:59:28 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+618 (618) in font CIDFont+F2

✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_143.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_157.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_157.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_180.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_180.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_194.pdf...
❌ Error processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_194.pdf: EOF marker not found
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_427.pdf...
❌ Error processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_427.pdf: EOF marker not found
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_341.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_341.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_355.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_355.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_433.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_433.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_369.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_369.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_382.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_382.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_396.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_396.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_397.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_397.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_383.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_383.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_368.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_368.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_354.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_354.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_432.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_432.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_426.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_426.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_340.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_340.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_195.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_195.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_181.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_181.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_156.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_156.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_142.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_142.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_022.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_022.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_036.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_036.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_208.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_208.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_220.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_220.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_234.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_234.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_239.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_239.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_211.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_211.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_205.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_205.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_013.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_013.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_007.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_007.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_167.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_167.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_173.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_173.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_198.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_198.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_359.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_359.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_365.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_365.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_403.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_403.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_417.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_417.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_371.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_371.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_416.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_416.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_370.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_370.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_364.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_364.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_402.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_402.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_358.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_358.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_199.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_199.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_172.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_172.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_166.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_166.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_006.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_006.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_012.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_012.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_204.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_204.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_210.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_210.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_238.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_238.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_206.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_206.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_212.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_212.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_038.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_038.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_004.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_004.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_010.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_010.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_158.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_158.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_170.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_170.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_164.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_164.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_428.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_428.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_372.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_372.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_414.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_414.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_400.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_400.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_366.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_366.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_399.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_399.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_398.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_398.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_401.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_401.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_367.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_367.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_373.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_373.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_415.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_415.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_429.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_429.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_165.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_165.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_171.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_171.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_159.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_159.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_011.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_011.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_005.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_005.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_039.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_039.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_213.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_213.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_207.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_207.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_203.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_203.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_217.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_217.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_001.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_001.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_015.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_015.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_029.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_029.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_175.pdf...
❌ Table not found in /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_175.pdf
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_161.pdf...
✅ Saved to: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_161.csv
Processing /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_pdfs/report_149.pdf...

# Cleaning

In [ ]:
import os

In [ ]:

directory = "/Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs"

In [ ]:
os.listdir(directory)

['report_266.csv',
 'report_272.csv',
 'report_058.csv',
 'report_064.csv',
 'report_070.csv',
 'report_138.csv',
 'report_110.csv',
 'report_104.csv',
 'report_448.csv',
 'report_312.csv',
 'report_306.csv',
 'report_307.csv',
 'report_313.csv',
 'report_449.csv',
 'report_105.csv',
 'report_111.csv',
 'report_139.csv',
 'report_071.csv',
 'report_065.csv',
 'report_298.csv',
 'report_273.csv',
 'report_267.csv',
 'report_259.csv',
 'report_271.csv',
 'report_265.csv',
 'report_107.csv',
 'report_113.csv',
 'report_339.csv',
 'report_305.csv',
 'report_311.csv',
 'report_310.csv',
 'report_304.csv',
 'report_338.csv',
 'report_112.csv',
 'report_106.csv',
 'report_099.csv',
 'report_066.csv',
 'report_072.csv',
 'report_264.csv',
 'report_270.csv',
 'report_258.csv',
 'report_274.csv',
 'report_260.csv',
 'report_248.csv',
 'report_076.csv',
 'report_062.csv',
 'report_089.csv',
 'report_102.csv',
 'report_116.csv',
 'report_300.csv',
 'report_314.csv',
 'report_328.csv',
 'report_329.csv',
 'report_315.csv',
 'report_301.csv',
 'report_117.csv',
 'report_103.csv',
 'report_088.csv',
 'report_063.csv',
 'report_077.csv',
 'report_249.csv',
 'report_261.csv',
 'report_275.csv',
 'report_263.csv',
 'report_288.csv',
 'report_061.csv',
 'report_115.csv',
 'report_101.csv',
 'report_129.csv',
 'report_317.csv',
 'report_303.csv',
 'report_302.csv',
 'report_316.csv',
 'report_128.csv',
 'report_100.csv',
 'report_048.csv',
 'report_074.csv',
 'report_060.csv',
 'report_289.csv',
 'report_276.csv',
 'report_262.csv',
 'report_239.csv',
 'report_211.csv',
 'report_173.csv',
 'report_167.csv',
 'report_198.csv',
 'report_359.csv',
 'report_371.csv',
 'report_403.csv',
 'report_402.csv',
 'report_370.csv',
 'report_358.csv',
 'report_199.csv',
 'report_172.csv',
 'report_210.csv',
 'report_204.csv',
 'report_238.csv',
 'report_206.csv',
 'report_038.csv',
 'report_158.csv',
 'report_170.csv',
 'report_428.csv',
 'report_366.csv',
 'report_400.csv',
 'report_414.csv',
 'report_372.csv',
 'report_399.csv',
 'report_398.csv',
 'report_415.csv',
 'report_373.csv',
 'report_401.csv',
 'report_429.csv',
 'report_171.csv',
 'report_165.csv',
 'report_159.csv',
 'report_039.csv',
 'report_213.csv',
 'report_217.csv',
 'report_203.csv',
 'report_015.csv',
 'report_029.csv',
 'report_161.csv',
 'report_149.csv',
 'report_405.csv',
 'report_363.csv',
 'report_377.csv',
 'report_411.csv',
 'report_439.csv',
 'report_388.csv',
 'report_389.csv',
 'report_438.csv',
 'report_376.csv',
 'report_410.csv',
 'report_404.csv',
 'report_362.csv',
 'report_148.csv',
 'report_174.csv',
 'report_160.csv',
 'report_028.csv',
 'report_014.csv',
 'report_202.csv',
 'report_216.csv',
 'report_214.csv',
 'report_228.csv',
 'report_016.csv',
 'report_176.csv',
 'report_162.csv',
 'report_189.csv',
 'report_412.csv',
 'report_360.csv',
 'report_406.csv',
 'report_349.csv',
 'report_361.csv',
 'report_407.csv',
 'report_413.csv',
 'report_188.csv',
 'report_163.csv',
 'report_177.csv',
 'report_017.csv',
 'report_229.csv',
 'report_215.csv',
 'report_201.csv',
 'report_224.csv',
 'report_026.csv',
 'report_032.csv',
 'report_152.csv',
 'report_146.csv',
 'report_191.csv',
 'report_185.csv',
 'report_378.csv',
 'report_350.csv',
 'report_436.csv',
 'report_422.csv',
 'report_393.csv',
 'report_387.csv',
 'report_386.csv',
 'report_392.csv',
 'report_345.csv',
 'report_437.csv',
 'report_379.csv',
 'report_184.csv',
 'report_190.csv',
 'report_147.csv',
 'report_153.csv',
 'report_033.csv',
 'report_027.csv',
 'report_231.csv',
 'report_225.csv',
 'report_219.csv',
 'report_233.csv',
 'report_227.csv',
 'report_019.csv',
 'report_031.csv',
 'report_025.csv',
 'report_145.csv',
 'report_151.csv',
 'report_186.csv',
 'report_192.csv',
 'report_409.csv',
 'report_347.csv',
 'report_435.csv',
 'report_353.csv',
 'report_384.csv',
 'report_390.csv',
 'report_391.csv',
 'report_385.csv',
 'report_434.csv',
 'report_352.csv',
 'report_420.csv',
 'report_408.csv',
 'report_193.csv',
 'report_187.csv',
 'report_150.csv',
 'report_144.csv',
 'report_178.csv',
 'report_024.csv',
 'report_030.csv',
 'report_018.csv',
 'report_226.csv',
 'report_232.csv',
 'report_236.csv',
 'report_222.csv',
 'report_020.csv',
 'report_140.csv',
 'report_154.csv',
 'report_168.csv',
 'report_183.csv',
 'report_197.csv',
 'report_424.csv',
 'report_342.csv',
 'report_356.csv',
 'report_430.csv',
 'report_418.csv',
 'report_381.csv',
 'report_395.csv',
 'report_394.csv',
 'report_380.csv',
 'report_419.csv',
 'report_357.csv',
 'report_425.csv',
 'report_343.csv',
 'report_182.csv',
 'report_169.csv',
 'report_155.csv',
 'report_141.csv',
 'report_021.csv',
 'report_223.csv',
 'report_237.csv',
 'report_221.csv',
 'report_235.csv',
 'report_209.csv',
 'report_023.csv',
 'report_037.csv',
 'report_157.csv',
 'report_143.csv',
 'report_180.csv',
 'report_433.csv',
 'report_355.csv',
 'report_341.csv',
 'report_369.csv',
 'report_396.csv',
 'report_382.csv',
 'report_383.csv',
 'report_397.csv',
 'report_368.csv',
 'report_340.csv',
 'report_426.csv',
 'report_432.csv',
 'report_354.csv',
 'report_181.csv',
 'report_195.csv',
 'report_142.csv',
 'report_156.csv',
 'report_036.csv',
 'report_022.csv',
 'report_208.csv',
 'report_234.csv',
 'report_220.csv',
 'report_247.csv',
 'report_253.csv',
 'report_284.csv',
 'report_079.csv',
 'report_045.csv',
 'report_051.csv',
 'report_086.csv',
 'report_092.csv',
 'report_119.csv',
 'report_131.csv',
 'report_125.csv',
 'report_455.csv',
 'report_333.csv',
 'report_327.csv',
 'report_441.csv',
 'report_326.csv',
 'report_440.csv',
 'report_454.csv',
 'report_130.csv',
 'report_118.csv',
 'report_093.csv',
 'report_087.csv',
 'report_050.csv',
 'report_044.csv',
 'report_078.csv',
 'report_291.csv',
 'report_285.csv',
 'report_252.csv',
 'report_246.csv',
 'report_278.csv',
 'report_250.csv',
 'report_244.csv',
 'report_293.csv',
 'report_287.csv',
 'report_052.csv',
 'report_091.csv',
 'report_085.csv',
 'report_126.csv',
 'report_132.csv',
 'report_324.csv',
 'report_330.csv',
 'report_456.csv',
 'report_331.csv',
 'report_443.csv',
 'report_325.csv',
 'report_319.csv',
 'report_133.csv',
 'report_127.csv',
 'report_084.csv',
 'report_090.csv',
 'report_047.csv',
 'report_053.csv',
 'report_286.csv',
 'report_292.csv',
 'report_245.csv',
 'report_251.csv',
 'report_279.csv',
 'report_255.csv',
 'report_241.csv',
 'report_296.csv',
 'report_282.csv',
 'report_057.csv',
 'report_043.csv',
 'report_094.csv',
 'report_080.csv',
 'report_123.csv',
 'report_137.csv',
 'report_447.csv',
 'report_335.csv',
 'report_309.csv',
 'report_308.csv',
 'report_452.csv',
 'report_334.csv',
 'report_320.csv',
 'report_446.csv',
 'report_136.csv',
 'report_122.csv',
 'report_081.csv',
 'report_095.csv',
 'report_042.csv',
 'report_056.csv',
 'report_283.csv',
 'report_297.csv',
 'report_268.csv',
 'report_240.csv',
 'report_254.csv',
 'report_256.csv',
 'report_295.csv',
 'report_040.csv',
 'report_054.csv',
 'report_083.csv',
 'report_097.csv',
 'report_134.csv',
 'report_120.csv',
 'report_336.csv',
 'report_450.csv',
 'report_444.csv',
 'report_322.csv',
 'report_445.csv',
 'report_323.csv',
 'report_337.csv',
 'report_451.csv',
 'report_109.csv',
 'report_121.csv',
 'report_135.csv',
 'report_096.csv',
 'report_082.csv',
 'report_069.csv',
 'report_055.csv',
 'report_041.csv',
 'report_294.csv',
 'report_280.csv',
 'report_257.csv',
 'report_243.csv']

In [ ]:
csv_files = [os.path.join(directory, f) for f in os.listdir(directory) if f.endswith('.csv')]
csv_files 
len(csv_files)

391

In [ ]:
def clean_csv_inplace(file_path):

    # Read all lines
    with open(file_path, 'r') as f:
        lines = f.readlines()
        
    if len(lines) <= 1:
        return
        
    original_count = len(lines)
    start_index = 0
    end_index = len(lines)

    first_line = lines[0].strip()
    has_title_problem = False
    if first_line and (
        (first_line[0].isdigit() and '.' in first_line[:5]) or  
        first_line.startswith('*') or
        ('Unnamed:' in first_line and first_line.count('Unnamed:') > 3)
    ):
        has_title_problem = True
        start_index = 1
        
    # Check if last line looks like a note
    last_line = lines[-1].strip()
    has_note_problem = False
    if last_line and (
        last_line.startswith('*') or  # "*Railways_ER ISTS added..."
        last_line.count(',') > 5 or  # mostly commas
        'w.e.f' in last_line.lower() or
        'added as an entity' in last_line.lower()
    ):
        has_note_problem = True
        end_index = len(lines) - 1

    if (has_title_problem or has_note_problem) and (end_index - start_index) > 0:
        print(f"Cleaning {file_path}:")
        cleaned_lines = lines[start_index:end_index]
        # Write back to same file
        with open(file_path, 'w') as f:
            f.writelines(cleaned_lines)

clean_csv_inplace('/Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_366.csv')

Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_366.csv:

In [ ]:
# Loop through all CSV files and apply cleaning only where needed
for csv_path in csv_files:
    clean_csv_inplace(csv_path)

Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_266.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_272.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_058.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_064.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_070.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_138.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_110.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_104.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_448.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_312.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_306.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_307.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_313.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_449.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_105.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_111.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_139.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_071.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_065.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_298.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_273.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_267.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_259.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_271.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_265.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_107.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_113.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_339.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_305.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_311.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_310.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_304.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_338.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_112.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_106.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_099.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_066.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_072.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_264.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_270.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_258.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_274.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_260.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_248.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_076.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_062.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_089.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_102.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_116.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_300.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_314.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_328.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_329.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_315.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_301.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_117.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_103.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_088.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_063.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_077.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_249.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_261.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_275.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_263.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_288.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_061.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_115.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_101.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_129.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_317.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_303.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_302.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_316.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_128.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_100.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_048.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_074.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_060.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_289.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_276.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_262.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_239.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_211.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_173.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_167.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_198.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_359.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_371.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_403.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_402.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_370.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_358.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_199.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_172.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_210.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_204.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_238.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_206.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_038.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_158.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_170.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_428.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_366.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_400.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_414.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_372.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_399.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_398.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_415.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_373.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_401.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_429.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_171.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_165.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_159.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_039.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_213.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_217.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_203.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_015.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_029.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_161.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_149.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_405.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_363.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_377.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_411.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_439.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_388.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_389.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_438.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_376.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_410.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_404.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_362.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_148.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_174.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_160.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_028.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_014.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_202.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_216.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_214.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_228.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_016.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_176.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_162.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_189.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_412.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_360.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_406.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_349.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_361.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_407.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_413.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_188.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_163.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_177.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_017.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_229.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_215.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_201.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_224.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_026.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_032.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_152.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_146.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_191.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_185.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_378.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_350.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_436.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_422.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_393.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_387.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_386.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_392.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_345.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_437.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_379.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_184.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_190.csv:
Cleaning /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_147.csv:

In [ ]:
def fix_state_formatting(file_path):
    try:
        with open(file_path, 'r') as f:
            lines = f.readlines()
                
        fixed_lines = []
        changes_made = False
        
        for i, line in enumerate(lines):
            # Skip header line
            if i == 0:
                fixed_lines.append(line)
                continue
            
            # Check if line has trailing comma and no leading comma
            stripped_line = line.strip()
            if stripped_line.endswith(',') and not stripped_line.startswith(','):
                # Split the line by commas
                parts = line.rstrip('\n').split(',')
                
                # Check if first part looks like a state name (not a region code)
                first_part = parts[0].strip()
                region_codes = ['NR', 'WR', 'SR', 'ER', 'NER']
                
                # If first part is not a region code and has trailing comma, it's likely a misplaced state
                if first_part not in region_codes and len(first_part) > 2:
                    # Move the state name to the second column
                    new_line = ',' + first_part
                    # Add the rest of the data (skip the trailing empty part from the comma)
                    if len(parts) > 1:
                        new_line += ',' + ','.join(parts[1:-1]) if parts[-1] == '' else ',' + ','.join(parts[1:])
                    new_line += '\n'
                    fixed_lines.append(new_line)
                    changes_made = True
                    continue
            
            # If no issues found, keep the line as is
            fixed_lines.append(line)
        
        # Write back only if changes were made
        if changes_made:
            with open(file_path, 'w') as f:
                f.writelines(fixed_lines)
            print(f"Fixed state formatting: {file_path}")
        else:
            print(f"No formatting issues found: {file_path}")
            
    except Exception as e:
        print(f"Error fixing {file_path}: {e}")
fix_state_formatting('/Users/aryankhurana/Electricity-Forecasting-Indian-States/report_450.csv')

No formatting issues found: /Users/aryankhurana/Electricity-Forecasting-Indian-States/report_450.csv

In [ ]:
for csv_path in csv_files:
    fix_state_formatting(csv_path)

Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_266.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_272.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_058.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_064.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_070.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_138.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_110.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_104.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_448.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_312.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_306.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_307.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_313.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_449.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_105.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_111.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_139.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_071.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_065.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_298.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_273.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_267.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_259.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_271.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_265.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_107.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_113.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_339.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_305.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_311.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_310.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_304.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_338.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_112.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_106.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_099.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_066.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_072.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_264.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_270.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_258.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_274.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_260.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_248.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_076.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_062.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_089.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_102.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_116.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_300.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_314.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_328.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_329.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_315.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_301.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_117.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_103.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_088.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_063.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_077.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_249.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_261.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_275.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_263.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_288.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_061.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_115.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_101.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_129.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_317.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_303.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_302.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_316.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_128.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_100.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_048.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_074.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_060.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_289.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_276.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_262.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_239.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_211.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_173.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_167.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_198.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_359.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_371.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_403.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_402.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_370.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_358.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_199.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_172.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_210.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_204.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_238.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_206.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_038.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_158.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_170.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_428.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_366.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_400.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_414.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_372.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_399.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_398.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_415.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_373.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_401.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_429.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_171.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_165.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_159.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_039.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_213.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_217.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_203.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_015.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_029.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_161.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_149.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_405.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_363.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_377.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_411.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_439.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_388.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_389.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_438.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_376.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_410.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_404.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_362.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_148.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_174.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_160.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_028.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_014.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_202.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_216.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_214.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_228.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_016.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_176.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_162.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_189.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_412.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_360.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_406.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_349.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_361.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_407.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_413.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_188.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_163.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_177.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_017.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_229.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_215.csv
Fixed state formatting: /Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/downloaded_csvs/report_201.csv

# Merging the csv files into one file

In [ ]:
import pandas as pd
import os

In [ ]:
import pandas as pd
import os

def merge_all_csv_files(csv_files, output_path):
    """
    Merge all CSV files into a single file based on States column
    """
    all_dataframes = []
    
    for i, csv_path in enumerate(csv_files):
        try:
            # Read the CSV file
            df = pd.read_csv(csv_path)
            
            # Drop Region column and any Unnamed columns
            columns_to_drop = []
            for col in df.columns:
                if col == 'Region' or col.startswith('Unnamed'):
                    columns_to_drop.append(col)
            
            if columns_to_drop:
                df = df.drop(columns=columns_to_drop)
                print(f"Dropped columns {columns_to_drop} from {os.path.basename(csv_path)}")
            
            # Check if States column exists
            if 'States' not in df.columns:
                print(f"Warning: No 'States' column found in {os.path.basename(csv_path)}, skipping...")
                continue
            
            # Remove rows where States column is empty or NaN
            df = df.dropna(subset=['States'])
            df = df[df['States'].str.strip() != '']
            
            if df.empty:
                print(f"Warning: No valid data in {os.path.basename(csv_path)}, skipping...")
                continue
            
            all_dataframes.append(df)
            print(f"Processed: {os.path.basename(csv_path)} - {len(df)} rows")
            
        except Exception as e:
            print(f"Error processing {csv_path}: {e}")
            continue
        
    # Start with the first dataframe
    merged_df = all_dataframes[0]
    
    # Merge each subsequent dataframe
    for i in range(1, len(all_dataframes)):
        merged_df = pd.merge(merged_df, all_dataframes[i], on='States', how='outer')   
    merged_df.to_csv(output_path, index=False)
    
    return merged_df

# Usage
output_file = "/Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/merged_electricity_data.csv"
merged_data = merge_all_csv_files(csv_files, output_file)

Dropped columns ['Region'] from report_266.csv
Processed: report_266.csv - 35 rows
Dropped columns ['Region'] from report_272.csv
Processed: report_272.csv - 35 rows
Dropped columns ['Region'] from report_058.csv
Processed: report_058.csv - 35 rows
Dropped columns ['Region'] from report_064.csv
Processed: report_064.csv - 39 rows
Dropped columns ['Region'] from report_070.csv
Processed: report_070.csv - 35 rows
Dropped columns ['Region'] from report_138.csv
Processed: report_138.csv - 35 rows
Dropped columns ['Region'] from report_110.csv
Processed: report_110.csv - 35 rows
Dropped columns ['Region'] from report_104.csv
Processed: report_104.csv - 35 rows
Dropped columns ['Region'] from report_448.csv
Processed: report_448.csv - 35 rows
Dropped columns ['Region'] from report_312.csv
Processed: report_312.csv - 39 rows
Dropped columns ['Region'] from report_306.csv
Processed: report_306.csv - 35 rows
Dropped columns ['Region'] from report_307.csv
Processed: report_307.csv - 35 rows
Dropped columns ['Region'] from report_313.csv
Processed: report_313.csv - 35 rows
Dropped columns ['Region'] from report_449.csv
Processed: report_449.csv - 35 rows
Dropped columns ['Region'] from report_105.csv
Processed: report_105.csv - 35 rows
Dropped columns ['Region'] from report_111.csv
Processed: report_111.csv - 35 rows
Dropped columns ['Region'] from report_139.csv
Processed: report_139.csv - 35 rows
Dropped columns ['Region'] from report_071.csv
Processed: report_071.csv - 35 rows
Dropped columns ['Region'] from report_065.csv
Processed: report_065.csv - 35 rows
Dropped columns ['Region'] from report_298.csv
Processed: report_298.csv - 34 rows
Dropped columns ['Region'] from report_273.csv
Processed: report_273.csv - 35 rows
Dropped columns ['Region'] from report_267.csv
Processed: report_267.csv - 35 rows
Dropped columns ['Region'] from report_259.csv
Processed: report_259.csv - 35 rows
Dropped columns ['Region'] from report_271.csv
Processed: report_271.csv - 35 rows
Dropped columns ['Region'] from report_265.csv
Processed: report_265.csv - 39 rows
Dropped columns ['Region'] from report_107.csv
Processed: report_107.csv - 35 rows
Dropped columns ['Region'] from report_113.csv
Processed: report_113.csv - 35 rows
Dropped columns ['Region'] from report_339.csv
Processed: report_339.csv - 35 rows
Dropped columns ['Region'] from report_305.csv
Processed: report_305.csv - 37 rows
Dropped columns ['Region'] from report_311.csv
Processed: report_311.csv - 35 rows
Dropped columns ['Region'] from report_310.csv
Processed: report_310.csv - 35 rows
Dropped columns ['Region'] from report_304.csv
Processed: report_304.csv - 39 rows
Dropped columns ['Region'] from report_338.csv
Processed: report_338.csv - 37 rows
Dropped columns ['Region'] from report_112.csv
Processed: report_112.csv - 35 rows
Dropped columns ['Region'] from report_106.csv
Processed: report_106.csv - 35 rows
Dropped columns ['Region'] from report_099.csv
Processed: report_099.csv - 36 rows
Dropped columns ['Region'] from report_066.csv
Processed: report_066.csv - 35 rows
Dropped columns ['Region'] from report_072.csv
Processed: report_072.csv - 35 rows
Dropped columns ['Region'] from report_264.csv
Processed: report_264.csv - 37 rows
Dropped columns ['Region'] from report_270.csv
Processed: report_270.csv - 39 rows
Dropped columns ['Region'] from report_258.csv
Processed: report_258.csv - 37 rows
Dropped columns ['Region'] from report_274.csv
Processed: report_274.csv - 35 rows
Dropped columns ['Region'] from report_260.csv
Processed: report_260.csv - 35 rows
Dropped columns ['Region'] from report_248.csv
Processed: report_248.csv - 37 rows
Dropped columns ['Region'] from report_076.csv
Processed: report_076.csv - 35 rows
Dropped columns ['Region'] from report_062.csv
Processed: report_062.csv - 34 rows
Dropped columns ['Region'] from report_089.csv
Processed: report_089.csv - 35 rows
Dropped columns ['Region'] from report_102.csv
Processed: report_102.csv - 39 rows
Dropped columns ['Region'] from report_116.csv
Processed: report_116.csv - 35 rows
Dropped columns ['Region'] from report_300.csv
Processed: report_300.csv - 39 rows
Dropped columns ['Region'] from report_314.csv
Processed: report_314.csv - 35 rows
Dropped columns ['Region'] from report_328.csv
Processed: report_328.csv - 35 rows
Dropped columns ['Region'] from report_329.csv
Processed: report_329.csv - 35 rows
Dropped columns ['Region'] from report_315.csv
Processed: report_315.csv - 35 rows
Dropped columns ['Region'] from report_301.csv
Processed: report_301.csv - 35 rows
Dropped columns ['Region'] from report_117.csv
Processed: report_117.csv - 39 rows
Dropped columns ['Region'] from report_103.csv
Processed: report_103.csv - 35 rows
Dropped columns ['Region'] from report_088.csv
Processed: report_088.csv - 35 rows
Dropped columns ['Region'] from report_063.csv
Processed: report_063.csv - 37 rows
Dropped columns ['Region'] from report_077.csv
Processed: report_077.csv - 35 rows
Dropped columns ['Region'] from report_249.csv
Processed: report_249.csv - 39 rows
Dropped columns ['Region'] from report_261.csv
Processed: report_261.csv - 35 rows
Dropped columns ['Region'] from report_275.csv
Processed: report_275.csv - 35 rows
Dropped columns ['Region'] from report_263.csv
Processed: report_263.csv - 39 rows
Dropped columns ['Region'] from report_288.csv
Processed: report_288.csv - 35 rows
Dropped columns ['Region'] from report_061.csv
Processed: report_061.csv - 35 rows
Dropped columns ['Region'] from report_115.csv
Processed: report_115.csv - 35 rows
Dropped columns ['Region'] from report_101.csv
Processed: report_101.csv - 37 rows
Dropped columns ['Region'] from report_129.csv
Processed: report_129.csv - 35 rows
Dropped columns ['Region'] from report_317.csv
Processed: report_317.csv - 35 rows
Dropped columns ['Region'] from report_303.csv
Processed: report_303.csv - 35 rows
Dropped columns ['Region'] from report_302.csv
Processed: report_302.csv - 37 rows
Dropped columns ['Region'] from report_316.csv
Processed: report_316.csv - 35 rows
Dropped columns ['Region'] from report_128.csv
Processed: report_128.csv - 35 rows
Dropped columns ['Region'] from report_100.csv
Processed: report_100.csv - 37 rows
Dropped columns ['Region'] from report_048.csv
Processed: report_048.csv - 35 rows
Dropped columns ['Region'] from report_074.csv
Processed: report_074.csv - 35 rows
Dropped columns ['Region'] from report_060.csv
Processed: report_060.csv - 39 rows
Dropped columns ['Region'] from report_289.csv
Processed: report_289.csv - 35 rows
Dropped columns ['Region'] from report_276.csv
Processed: report_276.csv - 35 rows
Dropped columns ['Region'] from report_262.csv
Processed: report_262.csv - 39 rows
Dropped columns ['Region'] from report_239.csv
Processed: report_239.csv - 35 rows
Dropped columns ['Region'] from report_211.csv
Processed: report_211.csv - 35 rows
Dropped columns ['Region'] from report_173.csv
Processed: report_173.csv - 35 rows
Dropped columns ['Region'] from report_167.csv
Processed: report_167.csv - 39 rows
Dropped columns ['Region'] from report_198.csv
Processed: report_198.csv - 35 rows
Dropped columns ['Region'] from report_359.csv
Processed: report_359.csv - 37 rows
Dropped columns ['Region'] from report_371.csv
Processed: report_371.csv - 37 rows
Dropped columns ['Region'] from report_403.csv
Processed: report_403.csv - 35 rows
Dropped columns ['Region'] from report_402.csv
Processed: report_402.csv - 35 rows
Dropped columns ['Region'] from report_370.csv
Processed: report_370.csv - 35 rows
Dropped columns ['Region'] from report_358.csv
Processed: report_358.csv - 35 rows
Dropped columns ['Region'] from report_199.csv
Processed: report_199.csv - 35 rows
Dropped columns ['Region'] from report_172.csv
Processed: report_172.csv - 35 rows
Dropped columns ['Region'] from report_210.csv
Processed: report_210.csv - 35 rows
Dropped columns ['Region'] from report_204.csv
Processed: report_204.csv - 35 rows
Dropped columns ['Region'] from report_238.csv
Processed: report_238.csv - 35 rows
Dropped columns ['Region'] from report_206.csv
Processed: report_206.csv - 35 rows
Dropped columns ['Region'] from report_038.csv
Processed: report_038.csv - 35 rows
Dropped columns ['Region'] from report_158.csv
Processed: report_158.csv - 35 rows
Dropped columns ['Region'] from report_170.csv
Processed: report_170.csv - 35 rows
Dropped columns ['Region'] from report_428.csv
Processed: report_428.csv - 35 rows
Dropped columns ['Region'] from report_366.csv
Processed: report_366.csv - 38 rows
Dropped columns ['Region'] from report_400.csv
Processed: report_400.csv - 35 rows
Dropped columns ['Region'] from report_414.csv
Processed: report_414.csv - 35 rows
Dropped columns ['Region'] from report_372.csv
Processed: report_372.csv - 35 rows
Dropped columns ['Region'] from report_399.csv
Processed: report_399.csv - 35 rows
Dropped columns ['Region'] from report_398.csv
Processed: report_398.csv - 39 rows
Dropped columns ['Region'] from report_415.csv
Processed: report_415.csv - 35 rows
Dropped columns ['Region'] from report_373.csv
Processed: report_373.csv - 35 rows
Dropped columns ['Region'] from report_401.csv
Processed: report_401.csv - 37 rows
Dropped columns ['Region'] from report_429.csv
Processed: report_429.csv - 35 rows
Dropped columns ['Region'] from report_171.csv
Processed: report_171.csv - 35 rows
Dropped columns ['Region'] from report_165.csv
Processed: report_165.csv - 34 rows
Dropped columns ['Region'] from report_159.csv
Processed: report_159.csv - 34 rows
Dropped columns ['Region'] from report_039.csv
Processed: report_039.csv - 35 rows
Dropped columns ['Region'] from report_213.csv
Processed: report_213.csv - 35 rows
Dropped columns ['Region'] from report_217.csv
Processed: report_217.csv - 35 rows
Dropped columns ['Region'] from report_203.csv
Processed: report_203.csv - 35 rows
Dropped columns ['Region'] from report_015.csv
Processed: report_015.csv - 35 rows
Dropped columns ['Region'] from report_029.csv
Processed: report_029.csv - 35 rows
Dropped columns ['Region'] from report_161.csv
Processed: report_161.csv - 39 rows
Dropped columns ['Region'] from report_149.csv
Processed: report_149.csv - 35 rows
Dropped columns ['Region'] from report_405.csv
Processed: report_405.csv - 35 rows
Dropped columns ['Region'] from report_363.csv
Processed: report_363.csv - 35 rows
Dropped columns ['Region'] from report_377.csv
Processed: report_377.csv - 35 rows
Dropped columns ['Region'] from report_411.csv
Processed: report_411.csv - 37 rows
Dropped columns ['Region'] from report_439.csv
Processed: report_439.csv - 35 rows
Dropped columns ['Region'] from report_388.csv
Processed: report_388.csv - 35 rows
Dropped columns ['Region'] from report_389.csv
Processed: report_389.csv - 35 rows
Dropped columns ['Region'] from report_438.csv
Processed: report_438.csv - 39 rows
Dropped columns ['Region'] from report_376.csv
Processed: report_376.csv - 35 rows
Dropped columns ['Region'] from report_410.csv
Processed: report_410.csv - 35 rows
Dropped columns ['Region'] from report_404.csv
Processed: report_404.csv - 37 rows
Dropped columns ['Region'] from report_362.csv
Processed: report_362.csv - 35 rows
Dropped columns ['Region'] from report_148.csv
Processed: report_148.csv - 35 rows
Dropped columns ['Region'] from report_174.csv
Processed: report_174.csv - 39 rows
Dropped columns ['Region'] from report_160.csv
Processed: report_160.csv - 35 rows
Dropped columns ['Region'] from report_028.csv
Processed: report_028.csv - 35 rows
Dropped columns ['Region'] from report_014.csv
Processed: report_014.csv - 35 rows
Dropped columns ['Region'] from report_202.csv
Processed: report_202.csv - 39 rows
Dropped columns ['Region'] from report_216.csv
Processed: report_216.csv - 35 rows
Dropped columns ['Region'] from report_214.csv
Processed: report_214.csv - 35 rows
Dropped columns ['Region'] from report_228.csv
Processed: report_228.csv - 39 rows
Dropped columns ['Region'] from report_016.csv
Processed: report_016.csv - 37 rows
Dropped columns ['Region'] from report_176.csv
Processed: report_176.csv - 34 rows
Dropped columns ['Region'] from report_162.csv
Processed: report_162.csv - 35 rows
Dropped columns ['Region'] from report_189.csv
Processed: report_189.csv - 35 rows
Dropped columns ['Region'] from report_412.csv
Processed: report_412.csv - 35 rows
Dropped columns ['Region'] from report_360.csv
Processed: report_360.csv - 35 rows
Dropped columns ['Region'] from report_406.csv
Processed: report_406.csv - 35 rows
Dropped columns ['Region'] from report_349.csv
Processed: report_349.csv - 35 rows
Dropped columns ['Region'] from report_361.csv
Processed: report_361.csv - 35 rows
Dropped columns ['Region'] from report_407.csv
Processed: report_407.csv - 34 rows
Dropped columns ['Region'] from report_413.csv
Processed: report_413.csv - 35 rows
Dropped columns ['Region'] from report_188.csv
Processed: report_188.csv - 35 rows
Dropped columns ['Region'] from report_163.csv
Processed: report_163.csv - 35 rows
Dropped columns ['Region'] from report_177.csv
Processed: report_177.csv - 39 rows
Dropped columns ['Region'] from report_017.csv
Processed: report_017.csv - 39 rows
Dropped columns ['Region'] from report_229.csv
Processed: report_229.csv - 35 rows
Dropped columns ['Region'] from report_215.csv
Processed: report_215.csv - 35 rows
Dropped columns ['Region'] from report_201.csv
Processed: report_201.csv - 35 rows
Dropped columns ['Region'] from report_224.csv
Processed: report_224.csv - 35 rows
Dropped columns ['Region'] from report_026.csv
Processed: report_026.csv - 34 rows
Dropped columns ['Region'] from report_032.csv
Processed: report_032.csv - 35 rows
Dropped columns ['Region'] from report_152.csv
Processed: report_152.csv - 39 rows
Dropped columns ['Region'] from report_146.csv
Processed: report_146.csv - 35 rows
Dropped columns ['Region'] from report_191.csv
Processed: report_191.csv - 35 rows
Dropped columns ['Region'] from report_185.csv
Processed: report_185.csv - 35 rows
Dropped columns ['Region'] from report_378.csv
Processed: report_378.csv - 35 rows
Dropped columns ['Region'] from report_350.csv
Processed: report_350.csv - 34 rows
Dropped columns ['Region'] from report_436.csv
Processed: report_436.csv - 35 rows
Dropped columns ['Region'] from report_422.csv
Processed: report_422.csv - 35 rows
Dropped columns ['Region'] from report_393.csv
Processed: report_393.csv - 39 rows
Dropped columns ['Region'] from report_387.csv
Processed: report_387.csv - 35 rows
Dropped columns ['Region'] from report_386.csv
Processed: report_386.csv - 35 rows
Dropped columns ['Region'] from report_392.csv
Processed: report_392.csv - 34 rows
Dropped columns ['Region'] from report_345.csv
Processed: report_345.csv - 35 rows
Dropped columns ['Region'] from report_437.csv
Processed: report_437.csv - 39 rows
Dropped columns ['Region'] from report_379.csv
Processed: report_379.csv - 35 rows
Dropped columns ['Region'] from report_184.csv
Processed: report_184.csv - 35 rows
Dropped columns ['Region'] from report_190.csv
Processed: report_190.csv - 35 rows
Dropped columns ['Region'] from report_147.csv
Processed: report_147.csv - 35 rows
Dropped columns ['Region'] from report_153.csv
Processed: report_153.csv - 35 rows
Dropped columns ['Region'] from report_033.csv
Processed: report_033.csv - 34 rows
Dropped columns ['Region'] from report_027.csv
Processed: report_027.csv - 39 rows
Dropped columns ['Region'] from report_231.csv
Processed: report_231.csv - 35 rows
Dropped columns ['Region'] from report_225.csv
Processed: report_225.csv - 35 rows
Dropped columns ['Unnamed: 0'] from report_219.csv
Processed: report_219.csv - 35 rows
Dropped columns ['Region'] from report_233.csv
Processed: report_233.csv - 39 rows
Dropped columns ['Region'] from report_227.csv
Processed: report_227.csv - 35 rows
Dropped columns ['Region'] from report_019.csv
Processed: report_019.csv - 35 rows
Dropped columns ['Region'] from report_031.csv
Processed: report_031.csv - 35 rows
Dropped columns ['Region'] from report_025.csv
Processed: report_025.csv - 35 rows
Dropped columns ['Region'] from report_145.csv
Processed: report_145.csv - 35 rows
Processed: report_151.csv - 35 rows
Dropped columns ['Region'] from report_186.csv
Processed: report_186.csv - 35 rows
Dropped columns ['Region'] from report_192.csv
Processed: report_192.csv - 35 rows
Dropped columns ['Region'] from report_409.csv
Processed: report_409.csv - 35 rows
Dropped columns ['Region'] from report_347.csv
Processed: report_347.csv - 35 rows
Dropped columns ['Region'] from report_435.csv
Processed: report_435.csv - 36 rows
Dropped columns ['Region'] from report_353.csv
Processed: report_353.csv - 35 rows
Dropped columns ['Region'] from report_384.csv
Processed: report_384.csv - 39 rows
Dropped columns ['Region'] from report_390.csv
Processed: report_390.csv - 34 rows
Dropped columns ['Region'] from report_391.csv
Processed: report_391.csv - 35 rows
Dropped columns ['Region'] from report_385.csv
Processed: report_385.csv - 35 rows
Dropped columns ['Region'] from report_434.csv
Processed: report_434.csv - 35 rows
Dropped columns ['Region'] from report_352.csv
Processed: report_352.csv - 35 rows
Dropped columns ['Region'] from report_420.csv
Processed: report_420.csv - 35 rows
Dropped columns ['Region'] from report_408.csv
Processed: report_408.csv - 35 rows
Dropped columns ['Region'] from report_193.csv
Processed: report_193.csv - 35 rows
Dropped columns ['Region'] from report_187.csv
Processed: report_187.csv - 35 rows
Dropped columns ['Region'] from report_150.csv
Processed: report_150.csv - 35 rows
Dropped columns ['Region'] from report_144.csv
Processed: report_144.csv - 35 rows
Dropped columns ['Region'] from report_178.csv
Processed: report_178.csv - 35 rows
Dropped columns ['Region'] from report_024.csv
Processed: report_024.csv - 35 rows
Dropped columns ['Region'] from report_030.csv
Processed: report_030.csv - 35 rows
Dropped columns ['Region'] from report_018.csv
Processed: report_018.csv - 34 rows
Dropped columns ['Region'] from report_226.csv
Processed: report_226.csv - 35 rows
Dropped columns ['Region'] from report_232.csv
Processed: report_232.csv - 35 rows
Dropped columns ['Region'] from report_236.csv
Processed: report_236.csv - 35 rows
Dropped columns ['Region'] from report_222.csv
Processed: report_222.csv - 35 rows
Dropped columns ['Region'] from report_020.csv
Processed: report_020.csv - 35 rows
Dropped columns ['Region'] from report_140.csv
Processed: report_140.csv - 35 rows
Dropped columns ['Region'] from report_154.csv
Processed: report_154.csv - 35 rows
Dropped columns ['Region'] from report_168.csv
Processed: report_168.csv - 35 rows
Dropped columns ['Region'] from report_183.csv
Processed: report_183.csv - 35 rows
Dropped columns ['Region'] from report_197.csv
Processed: report_197.csv - 35 rows
Dropped columns ['Region'] from report_424.csv
Processed: report_424.csv - 35 rows
Dropped columns ['Region'] from report_342.csv
Processed: report_342.csv - 39 rows
Dropped columns ['Region'] from report_356.csv
Processed: report_356.csv - 35 rows
Dropped columns ['Region'] from report_430.csv
Processed: report_430.csv - 35 rows
Dropped columns ['Region'] from report_418.csv
Processed: report_418.csv - 34 rows
Dropped columns ['Region'] from report_381.csv
Processed: report_381.csv - 35 rows
Dropped columns ['Region'] from report_395.csv
Processed: report_395.csv - 35 rows
Dropped columns ['Region'] from report_394.csv
Processed: report_394.csv - 35 rows
Dropped columns ['Region'] from report_380.csv
Processed: report_380.csv - 35 rows
Dropped columns ['Region'] from report_419.csv
Processed: report_419.csv - 35 rows
Dropped columns ['Region'] from report_357.csv
Processed: report_357.csv - 34 rows
Dropped columns ['Region'] from report_425.csv
Processed: report_425.csv - 35 rows
Dropped columns ['Region'] from report_343.csv
Processed: report_343.csv - 35 rows

# Cleaning the data

In [262]:
df = pd.read_csv('/Users/aryankhurana/Electricity-Forecasting-Indian-States/artifacts/merged_electricity_data.csv')
df.head(50)

,States,04-04-2022,05-04-2022,06-04-2022,07-04-2022,08-04-2022,09-04-2022,10-04-2022,08-01-2018,09-01-2018,...,15-09-2023,16-09-2023,17-09-2023,11-04-2022,12-04-2022,13-04-2022,14-04-2022,15-04-2022,16-04-2022,17-04-2022
0,ALL INDIA TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4795.3,4654.1,4284.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AMNSIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.0,18.5,18.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Andhra Pradesh,220.8,218.7,205.9,213.1,217.1,211.8,207.4,162.2,165.2,...,230.9,230.3,226.5,209.4,208.8,209.2,213.0,211.6,210.5,200.7
3,Arunachal Pradesh,2.2,2.3,2.4,2.4,2.4,2.3,2.3,2.3,2.2,...,3.0,2.9,3.1,2.4,2.4,2.2,2.2,1.5,2.0,2.1
4,Assam,23.8,26.3,26.8,27.8,27.9,26.1,22.9,22.8,23.6,...,50.0,49.1,47.1,23.2,27.8,28.6,22.1,19.8,20.7,21.2
5,BALCO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.4,12.4,12.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Bihar,114.4,110.1,112.7,119.2,118.9,116.7,110.0,71.5,73.9,...,147.9,152.5,152.9,114.1,117.3,121.0,122.4,118.8,123.6,125.2
7,Chandigarh,4.5,4.6,4.6,4.6,4.7,4.6,4.3,3.7,3.8,...,6.6,6.2,6.0,5.0,5.3,5.5,4.7,4.6,4.6,4.3
8,Chhattisgarh,123.3,125.8,123.4,122.7,124.8,122.2,120.2,73.3,73.4,...,92.8,96.5,93.7,120.6,122.6,120.5,123.9,123.7,125.0,123.4
9,DD,7.5,7.9,8.0,8.0,8.2,8.2,7.4,7.0,7.2,...,NaN,NaN,NaN,7.7,8.0,8.1,8.0,8.1,8.0,7.3
10,DD*,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,DNH,18.4,19.6,20.2,19.2,20.3,20.5,20.1,17.3,17.6,...,NaN,NaN,NaN,20.5,20.5,20.1,20.4,20.2,20.1,19.9
12,DNH*,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,DNHDDPDCL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,29.9,30.2,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,DVC,77.4,79.5,80.3,76.7,80.3,76.8,75.4,69.2,70.8,...,77.4,79.2,75.4,74.9,75.0,78.8,79.7,78.5,79.4,78.5
15,Delhi,94.5,95.7,97.9,99.4,101.9,100.7,98.5,68.6,68.9,...,131.3,121.1,108.2,108.8,110.0,108.8,105.5,104.7,103.3,101.7
16,Essar steel,17.1,15.5,16.2,15.6,15.4,16.8,17.1,8.7,9.9,...,NaN,NaN,NaN,17.2,17.1,16.7,16.9,16.2,16.9,16.9
17,Goa,14.6,14.4,14.1,14.5,14.4,14.9,13.2,9.2,9.2,...,14.5,14.2,13.9,13.5,14.5,14.7,14.1,14.1,14.3,13.8
18,Gujarat,424.5,430.6,428.3,436.2,445.0,443.3,419.0,296.2,299.4,...,461.8,440.9,369.0,426.2,433.3,431.7,438.8,428.6,433.8,418.1
19,HP,31.7,31.2,32.0,32.7,32.7,32.8,29.4,26.6,27.6,...,35.0,35.1,30.4,31.9,33.4,33.6,32.7,30.7,33.0,30.7
20,Haryana,139.2,141.7,138.7,145.0,149.0,146.6,138.2,123.3,128.5,...,236.5,217.1,177.5,150.1,155.5,160.0,153.4,156.7,157.9,147.1
21,J&K,46.5,46.8,46.8,46.3,50.9,48.6,51.8,46.7,47.1,...,47.2,49.0,47.7,48.6,49.5,46.1,46.3,50.1,47.6,50.1
22,Jharkhand,33.9,34.7,34.1,33.2,34.0,33.8,29.8,24.8,24.5,...,39.1,40.2,37.9,33.4,32.7,32.5,35.7,36.6,37.0,36.0
23,Karnataka,271.5,270.9,271.3,277.4,282.9,271.5,250.1,202.6,204.7,...,262.1,254.4,231.9,270.5,269.3,262.1,236.1,213.2,212.7,190.5
24,Kerala,85.0,86.0,80.4,81.2,79.0,73.5,69.8,64.2,64.7,...,78.8,78.9,70.5,78.9,78.0,76.7,73.0,69.6,80.3,76.2
25,MP,257.8,262.7,263.8,257.9,256.9,263.7,269.9,225.2,227.1,...,223.1,193.9,191.3,268.8,257.0,261.5,275.4,278.1,278.0,275.9
26,Maharashtra,611.1,623.3,615.4,611.3,612.0,611.9,590.0,405.2,409.3,...,527.2,519.8,508.6,591.6,598.2,594.2,601.0,609.8,609.7,591.4
27,Manipur,2.6,2.7,2.6,2.6,2.5,2.8,2.5,2.8,2.7,...,2.8,2.7,2.8,2.6,2.6,2.4,2.3,1.9,2.3,2.4
28,Meghalaya,5.1,5.8,6.2,6.5,6.4,6.3,5.5,6.7,6.4,...,5.6,6.0,5.6,5.5,6.2,5.8,4.9,4.7,5.1,4.7
29,Mizoram,1.7,1.7,1.8,1.7,1.8,1.8,1.8,1.8,1.8,...,1.7,1.8,1.7,1.7,1.8,1.7,1.7,1.5,1.7,1.7
30,NER Meghalaya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Nagaland,2.2,2.4,2.2,2.2,2.2,2.2,2.3,2.0,2.1,...,2.5,2.5,3.0,2.4,2.5,1.9,2.3,1.7,2.1,2.1
32,Odisha,108.5,109.3,113.5,112.7,115.0,120.3,125.5,68.5,67.7,...,116.2,113.4,122.4,125.4,120.3,117.3,120.6,116.9,121.6,121.1
33,Pondy,9.1,9.2,9.3,9.3,9.4,9.3,8.1,6.0,6.3,...,10.1,10.1,8.4,8.6,9.0,8.7,8.0,8.8,9.3,8.6
34,Punjab,149.5,142.2,147.1,161.3,160.0,158.9,147.2,105.4,108.2,...,276.5,268.5,196.0,158.5,159.3,165.8,151.5,152.5,161.1,151.4
35,Railways_ER ISTS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Railways_ER ISTS*,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.2,0.2,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Railways_NR ISTS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.6,3.4,3.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Rajasthan,249.4,253.7,254.3,249.6,260.1,262.9,256.4,209.3,211.5,...,307.7,275.9,235.3,263.2,258.5,248.6,258.7,263.0,265.8,264.7
39,Sikkim,1.7,1.8,1.8,1.6,1.3,1.0,1.0,1.6,1.6,...,1.4,1.3,0.9,1.6,1.8,1.7,1.7,1.7,1.4,1.2
40,Tamil Nadu,363.1,367.1,367.6,372.7,372.7,360.1,320.3,288.9,292.5,...,365.2,348.7,314.3,339.2,345.0,336.8,313.2,324.1,335.8,296.9
41,Telangana,265.7,266.0,265.7,267.1,265.0,253.0,254.4,177.8,179.7,...,245.0,254.2,259.1,252.3,254.6,250.5,223.3,239.6,243.7,235.7
42,Tripura,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.1,6.4,5.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,UP,397.5,395.7,405.1,407.8,412.5,416.9,407.2,305.3,310.5,...,476.3,459.3,429.2,424.4,431.7,433.2,421.5,406.6,421.7,422.4
44,Uttarakhand,39.8,40.6,37.5,38.8,40.9,41.6,39.0,38.3,39.2,...,45.8,45.8,39.5,41.7,40.7,41.9,41.2,40.7,38.2,39.9
45,West Bengal,178.1,185.0,185.3,188.2,186.6,186.9,178.2,103.3,111.5,...,203.3,211.6,205.8,186.4,194.6,195.6,193.2,187.1,197.2,186.4

In [263]:
df.drop(0,axis=0, inplace=True)  # Drop the first row if it is not needed

In [264]:
df.head(50)

,States,04-04-2022,05-04-2022,06-04-2022,07-04-2022,08-04-2022,09-04-2022,10-04-2022,08-01-2018,09-01-2018,...,15-09-2023,16-09-2023,17-09-2023,11-04-2022,12-04-2022,13-04-2022,14-04-2022,15-04-2022,16-04-2022,17-04-2022
1,AMNSIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.0,18.5,18.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Andhra Pradesh,220.8,218.7,205.9,213.1,217.1,211.8,207.4,162.2,165.2,...,230.9,230.3,226.5,209.4,208.8,209.2,213.0,211.6,210.5,200.7
3,Arunachal Pradesh,2.2,2.3,2.4,2.4,2.4,2.3,2.3,2.3,2.2,...,3.0,2.9,3.1,2.4,2.4,2.2,2.2,1.5,2.0,2.1
4,Assam,23.8,26.3,26.8,27.8,27.9,26.1,22.9,22.8,23.6,...,50.0,49.1,47.1,23.2,27.8,28.6,22.1,19.8,20.7,21.2
5,BALCO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.4,12.4,12.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Bihar,114.4,110.1,112.7,119.2,118.9,116.7,110.0,71.5,73.9,...,147.9,152.5,152.9,114.1,117.3,121.0,122.4,118.8,123.6,125.2
7,Chandigarh,4.5,4.6,4.6,4.6,4.7,4.6,4.3,3.7,3.8,...,6.6,6.2,6.0,5.0,5.3,5.5,4.7,4.6,4.6,4.3
8,Chhattisgarh,123.3,125.8,123.4,122.7,124.8,122.2,120.2,73.3,73.4,...,92.8,96.5,93.7,120.6,122.6,120.5,123.9,123.7,125.0,123.4
9,DD,7.5,7.9,8.0,8.0,8.2,8.2,7.4,7.0,7.2,...,NaN,NaN,NaN,7.7,8.0,8.1,8.0,8.1,8.0,7.3
10,DD*,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,DNH,18.4,19.6,20.2,19.2,20.3,20.5,20.1,17.3,17.6,...,NaN,NaN,NaN,20.5,20.5,20.1,20.4,20.2,20.1,19.9
12,DNH*,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,DNHDDPDCL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,29.9,30.2,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,DVC,77.4,79.5,80.3,76.7,80.3,76.8,75.4,69.2,70.8,...,77.4,79.2,75.4,74.9,75.0,78.8,79.7,78.5,79.4,78.5
15,Delhi,94.5,95.7,97.9,99.4,101.9,100.7,98.5,68.6,68.9,...,131.3,121.1,108.2,108.8,110.0,108.8,105.5,104.7,103.3,101.7
16,Essar steel,17.1,15.5,16.2,15.6,15.4,16.8,17.1,8.7,9.9,...,NaN,NaN,NaN,17.2,17.1,16.7,16.9,16.2,16.9,16.9
17,Goa,14.6,14.4,14.1,14.5,14.4,14.9,13.2,9.2,9.2,...,14.5,14.2,13.9,13.5,14.5,14.7,14.1,14.1,14.3,13.8
18,Gujarat,424.5,430.6,428.3,436.2,445.0,443.3,419.0,296.2,299.4,...,461.8,440.9,369.0,426.2,433.3,431.7,438.8,428.6,433.8,418.1
19,HP,31.7,31.2,32.0,32.7,32.7,32.8,29.4,26.6,27.6,...,35.0,35.1,30.4,31.9,33.4,33.6,32.7,30.7,33.0,30.7
20,Haryana,139.2,141.7,138.7,145.0,149.0,146.6,138.2,123.3,128.5,...,236.5,217.1,177.5,150.1,155.5,160.0,153.4,156.7,157.9,147.1
21,J&K,46.5,46.8,46.8,46.3,50.9,48.6,51.8,46.7,47.1,...,47.2,49.0,47.7,48.6,49.5,46.1,46.3,50.1,47.6,50.1
22,Jharkhand,33.9,34.7,34.1,33.2,34.0,33.8,29.8,24.8,24.5,...,39.1,40.2,37.9,33.4,32.7,32.5,35.7,36.6,37.0,36.0
23,Karnataka,271.5,270.9,271.3,277.4,282.9,271.5,250.1,202.6,204.7,...,262.1,254.4,231.9,270.5,269.3,262.1,236.1,213.2,212.7,190.5
24,Kerala,85.0,86.0,80.4,81.2,79.0,73.5,69.8,64.2,64.7,...,78.8,78.9,70.5,78.9,78.0,76.7,73.0,69.6,80.3,76.2
25,MP,257.8,262.7,263.8,257.9,256.9,263.7,269.9,225.2,227.1,...,223.1,193.9,191.3,268.8,257.0,261.5,275.4,278.1,278.0,275.9
26,Maharashtra,611.1,623.3,615.4,611.3,612.0,611.9,590.0,405.2,409.3,...,527.2,519.8,508.6,591.6,598.2,594.2,601.0,609.8,609.7,591.4
27,Manipur,2.6,2.7,2.6,2.6,2.5,2.8,2.5,2.8,2.7,...,2.8,2.7,2.8,2.6,2.6,2.4,2.3,1.9,2.3,2.4
28,Meghalaya,5.1,5.8,6.2,6.5,6.4,6.3,5.5,6.7,6.4,...,5.6,6.0,5.6,5.5,6.2,5.8,4.9,4.7,5.1,4.7
29,Mizoram,1.7,1.7,1.8,1.7,1.8,1.8,1.8,1.8,1.8,...,1.7,1.8,1.7,1.7,1.8,1.7,1.7,1.5,1.7,1.7
30,NER Meghalaya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Nagaland,2.2,2.4,2.2,2.2,2.2,2.2,2.3,2.0,2.1,...,2.5,2.5,3.0,2.4,2.5,1.9,2.3,1.7,2.1,2.1
32,Odisha,108.5,109.3,113.5,112.7,115.0,120.3,125.5,68.5,67.7,...,116.2,113.4,122.4,125.4,120.3,117.3,120.6,116.9,121.6,121.1
33,Pondy,9.1,9.2,9.3,9.3,9.4,9.3,8.1,6.0,6.3,...,10.1,10.1,8.4,8.6,9.0,8.7,8.0,8.8,9.3,8.6
34,Punjab,149.5,142.2,147.1,161.3,160.0,158.9,147.2,105.4,108.2,...,276.5,268.5,196.0,158.5,159.3,165.8,151.5,152.5,161.1,151.4
35,Railways_ER ISTS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Railways_ER ISTS*,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.2,0.2,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Railways_NR ISTS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.6,3.4,3.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Rajasthan,249.4,253.7,254.3,249.6,260.1,262.9,256.4,209.3,211.5,...,307.7,275.9,235.3,263.2,258.5,248.6,258.7,263.0,265.8,264.7
39,Sikkim,1.7,1.8,1.8,1.6,1.3,1.0,1.0,1.6,1.6,...,1.4,1.3,0.9,1.6,1.8,1.7,1.7,1.7,1.4,1.2
40,Tamil Nadu,363.1,367.1,367.6,372.7,372.7,360.1,320.3,288.9,292.5,...,365.2,348.7,314.3,339.2,345.0,336.8,313.2,324.1,335.8,296.9
41,Telangana,265.7,266.0,265.7,267.1,265.0,253.0,254.4,177.8,179.7,...,245.0,254.2,259.1,252.3,254.6,250.5,223.3,239.6,243.7,235.7
42,Tripura,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.1,6.4,5.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,UP,397.5,395.7,405.1,407.8,412.5,416.9,407.2,305.3,310.5,...,476.3,459.3,429.2,424.4,431.7,433.2,421.5,406.6,421.7,422.4
44,Uttarakhand,39.8,40.6,37.5,38.8,40.9,41.6,39.0,38.3,39.2,...,45.8,45.8,39.5,41.7,40.7,41.9,41.2,40.7,38.2,39.9
45,West Bengal,178.1,185.0,185.3,188.2,186.6,186.9,178.2,103.3,111.5,...,203.3,211.6,205.8,186.4,194.6,195.6,193.2,187.1,197.2,186.4

In [265]:
import numpy as np

In [266]:
def fill_from_starred_rows(df, base_states=['DD', 'DNH','Railways_ER ISTS']):
    """
    Fill NaN values in base state rows with values from their starred counterparts
    
    Parameters:
    df: DataFrame with electricity data
    base_states: List of state names to process (without asterisk)
    """
    df_result = df.copy()
    
    for state in base_states:
        base_mask = df_result['States'] == state
        star_mask = df_result['States'] == f'{state}*'
        
        if base_mask.any() and star_mask.any():
            base_idx = df_result[base_mask].index[0]
            star_idx = df_result[star_mask].index[0]
            
            # Get numeric columns only
            numeric_cols = df_result.select_dtypes(include=[np.number]).columns
            
            # Fill NaN values in base row with values from starred row
            for col in numeric_cols:
                if pd.isna(df_result.loc[base_idx, col]) and not pd.isna(df_result.loc[star_idx, col]):
                    df_result.loc[base_idx, col] = df_result.loc[star_idx, col]
            
            # Remove the starred row after filling
            df_result = df_result.drop(star_idx)
    
    return df_result.reset_index(drop=True)

# Usage
df = fill_from_starred_rows(df, ['DD', 'DNH'])

In [267]:
df.head(50)

,States,04-04-2022,05-04-2022,06-04-2022,07-04-2022,08-04-2022,09-04-2022,10-04-2022,08-01-2018,09-01-2018,...,15-09-2023,16-09-2023,17-09-2023,11-04-2022,12-04-2022,13-04-2022,14-04-2022,15-04-2022,16-04-2022,17-04-2022
0,AMNSIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.0,18.5,18.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Andhra Pradesh,220.8,218.7,205.9,213.1,217.1,211.8,207.4,162.2,165.2,...,230.9,230.3,226.5,209.4,208.8,209.2,213.0,211.6,210.5,200.7
2,Arunachal Pradesh,2.2,2.3,2.4,2.4,2.4,2.3,2.3,2.3,2.2,...,3.0,2.9,3.1,2.4,2.4,2.2,2.2,1.5,2.0,2.1
3,Assam,23.8,26.3,26.8,27.8,27.9,26.1,22.9,22.8,23.6,...,50.0,49.1,47.1,23.2,27.8,28.6,22.1,19.8,20.7,21.2
4,BALCO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.4,12.4,12.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Bihar,114.4,110.1,112.7,119.2,118.9,116.7,110.0,71.5,73.9,...,147.9,152.5,152.9,114.1,117.3,121.0,122.4,118.8,123.6,125.2
6,Chandigarh,4.5,4.6,4.6,4.6,4.7,4.6,4.3,3.7,3.8,...,6.6,6.2,6.0,5.0,5.3,5.5,4.7,4.6,4.6,4.3
7,Chhattisgarh,123.3,125.8,123.4,122.7,124.8,122.2,120.2,73.3,73.4,...,92.8,96.5,93.7,120.6,122.6,120.5,123.9,123.7,125.0,123.4
8,DD,7.5,7.9,8.0,8.0,8.2,8.2,7.4,7.0,7.2,...,NaN,NaN,NaN,7.7,8.0,8.1,8.0,8.1,8.0,7.3
9,DNH,18.4,19.6,20.2,19.2,20.3,20.5,20.1,17.3,17.6,...,NaN,NaN,NaN,20.5,20.5,20.1,20.4,20.2,20.1,19.9
10,DNHDDPDCL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,29.9,30.2,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,DVC,77.4,79.5,80.3,76.7,80.3,76.8,75.4,69.2,70.8,...,77.4,79.2,75.4,74.9,75.0,78.8,79.7,78.5,79.4,78.5
12,Delhi,94.5,95.7,97.9,99.4,101.9,100.7,98.5,68.6,68.9,...,131.3,121.1,108.2,108.8,110.0,108.8,105.5,104.7,103.3,101.7
13,Essar steel,17.1,15.5,16.2,15.6,15.4,16.8,17.1,8.7,9.9,...,NaN,NaN,NaN,17.2,17.1,16.7,16.9,16.2,16.9,16.9
14,Goa,14.6,14.4,14.1,14.5,14.4,14.9,13.2,9.2,9.2,...,14.5,14.2,13.9,13.5,14.5,14.7,14.1,14.1,14.3,13.8
15,Gujarat,424.5,430.6,428.3,436.2,445.0,443.3,419.0,296.2,299.4,...,461.8,440.9,369.0,426.2,433.3,431.7,438.8,428.6,433.8,418.1
16,HP,31.7,31.2,32.0,32.7,32.7,32.8,29.4,26.6,27.6,...,35.0,35.1,30.4,31.9,33.4,33.6,32.7,30.7,33.0,30.7
17,Haryana,139.2,141.7,138.7,145.0,149.0,146.6,138.2,123.3,128.5,...,236.5,217.1,177.5,150.1,155.5,160.0,153.4,156.7,157.9,147.1
18,J&K,46.5,46.8,46.8,46.3,50.9,48.6,51.8,46.7,47.1,...,47.2,49.0,47.7,48.6,49.5,46.1,46.3,50.1,47.6,50.1
19,Jharkhand,33.9,34.7,34.1,33.2,34.0,33.8,29.8,24.8,24.5,...,39.1,40.2,37.9,33.4,32.7,32.5,35.7,36.6,37.0,36.0
20,Karnataka,271.5,270.9,271.3,277.4,282.9,271.5,250.1,202.6,204.7,...,262.1,254.4,231.9,270.5,269.3,262.1,236.1,213.2,212.7,190.5
21,Kerala,85.0,86.0,80.4,81.2,79.0,73.5,69.8,64.2,64.7,...,78.8,78.9,70.5,78.9,78.0,76.7,73.0,69.6,80.3,76.2
22,MP,257.8,262.7,263.8,257.9,256.9,263.7,269.9,225.2,227.1,...,223.1,193.9,191.3,268.8,257.0,261.5,275.4,278.1,278.0,275.9
23,Maharashtra,611.1,623.3,615.4,611.3,612.0,611.9,590.0,405.2,409.3,...,527.2,519.8,508.6,591.6,598.2,594.2,601.0,609.8,609.7,591.4
24,Manipur,2.6,2.7,2.6,2.6,2.5,2.8,2.5,2.8,2.7,...,2.8,2.7,2.8,2.6,2.6,2.4,2.3,1.9,2.3,2.4
25,Meghalaya,5.1,5.8,6.2,6.5,6.4,6.3,5.5,6.7,6.4,...,5.6,6.0,5.6,5.5,6.2,5.8,4.9,4.7,5.1,4.7
26,Mizoram,1.7,1.7,1.8,1.7,1.8,1.8,1.8,1.8,1.8,...,1.7,1.8,1.7,1.7,1.8,1.7,1.7,1.5,1.7,1.7
27,NER Meghalaya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Nagaland,2.2,2.4,2.2,2.2,2.2,2.2,2.3,2.0,2.1,...,2.5,2.5,3.0,2.4,2.5,1.9,2.3,1.7,2.1,2.1
29,Odisha,108.5,109.3,113.5,112.7,115.0,120.3,125.5,68.5,67.7,...,116.2,113.4,122.4,125.4,120.3,117.3,120.6,116.9,121.6,121.1
30,Pondy,9.1,9.2,9.3,9.3,9.4,9.3,8.1,6.0,6.3,...,10.1,10.1,8.4,8.6,9.0,8.7,8.0,8.8,9.3,8.6
31,Punjab,149.5,142.2,147.1,161.3,160.0,158.9,147.2,105.4,108.2,...,276.5,268.5,196.0,158.5,159.3,165.8,151.5,152.5,161.1,151.4
32,Railways_ER ISTS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Railways_ER ISTS*,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.2,0.2,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Railways_NR ISTS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.6,3.4,3.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Rajasthan,249.4,253.7,254.3,249.6,260.1,262.9,256.4,209.3,211.5,...,307.7,275.9,235.3,263.2,258.5,248.6,258.7,263.0,265.8,264.7
36,Sikkim,1.7,1.8,1.8,1.6,1.3,1.0,1.0,1.6,1.6,...,1.4,1.3,0.9,1.6,1.8,1.7,1.7,1.7,1.4,1.2
37,Tamil Nadu,363.1,367.1,367.6,372.7,372.7,360.1,320.3,288.9,292.5,...,365.2,348.7,314.3,339.2,345.0,336.8,313.2,324.1,335.8,296.9
38,Telangana,265.7,266.0,265.7,267.1,265.0,253.0,254.4,177.8,179.7,...,245.0,254.2,259.1,252.3,254.6,250.5,223.3,239.6,243.7,235.7
39,Tripura,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.1,6.4,5.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,UP,397.5,395.7,405.1,407.8,412.5,416.9,407.2,305.3,310.5,...,476.3,459.3,429.2,424.4,431.7,433.2,421.5,406.6,421.7,422.4
41,Uttarakhand,39.8,40.6,37.5,38.8,40.9,41.6,39.0,38.3,39.2,...,45.8,45.8,39.5,41.7,40.7,41.9,41.2,40.7,38.2,39.9
42,West Bengal,178.1,185.0,185.3,188.2,186.6,186.9,178.2,103.3,111.5,...,203.3,211.6,205.8,186.4,194.6,195.6,193.2,187.1,197.2,186.4

In [268]:
def add_total_consumption_row(df):
    """
    Add a 'Total Consumption' row that sums all electricity consumption
    """
    df_result = df.copy()
    
    # Get all numeric columns (these should be the date columns with consumption data)
    numeric_cols = df_result.select_dtypes(include=[np.number]).columns
    
    # Calculate the sum for each numeric column, ignoring NaN values
    total_row = {}
    total_row['States'] = 'Total Consumption'
    
    for col in numeric_cols:
        total_row[col] = df_result[col].sum(skipna=True)
    
    # Convert to DataFrame row and append
    total_df = pd.DataFrame([total_row])
    df_result = pd.concat([df_result, total_df], ignore_index=True)
    
    return df_result

# Apply the function
df = add_total_consumption_row(df)
df.head(50)

,States,04-04-2022,05-04-2022,06-04-2022,07-04-2022,08-04-2022,09-04-2022,10-04-2022,08-01-2018,09-01-2018,...,15-09-2023,16-09-2023,17-09-2023,11-04-2022,12-04-2022,13-04-2022,14-04-2022,15-04-2022,16-04-2022,17-04-2022
0,AMNSIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.0,18.5,18.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Andhra Pradesh,220.8,218.7,205.9,213.1,217.1,211.8,207.4,162.2,165.2,...,230.9,230.3,226.5,209.4,208.8,209.2,213.0,211.6,210.5,200.7
2,Arunachal Pradesh,2.2,2.3,2.4,2.4,2.4,2.3,2.3,2.3,2.2,...,3.0,2.9,3.1,2.4,2.4,2.2,2.2,1.5,2.0,2.1
3,Assam,23.8,26.3,26.8,27.8,27.9,26.1,22.9,22.8,23.6,...,50.0,49.1,47.1,23.2,27.8,28.6,22.1,19.8,20.7,21.2
4,BALCO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.4,12.4,12.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Bihar,114.4,110.1,112.7,119.2,118.9,116.7,110.0,71.5,73.9,...,147.9,152.5,152.9,114.1,117.3,121.0,122.4,118.8,123.6,125.2
6,Chandigarh,4.5,4.6,4.6,4.6,4.7,4.6,4.3,3.7,3.8,...,6.6,6.2,6.0,5.0,5.3,5.5,4.7,4.6,4.6,4.3
7,Chhattisgarh,123.3,125.8,123.4,122.7,124.8,122.2,120.2,73.3,73.4,...,92.8,96.5,93.7,120.6,122.6,120.5,123.9,123.7,125.0,123.4
8,DD,7.5,7.9,8.0,8.0,8.2,8.2,7.4,7.0,7.2,...,NaN,NaN,NaN,7.7,8.0,8.1,8.0,8.1,8.0,7.3
9,DNH,18.4,19.6,20.2,19.2,20.3,20.5,20.1,17.3,17.6,...,NaN,NaN,NaN,20.5,20.5,20.1,20.4,20.2,20.1,19.9
10,DNHDDPDCL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,29.9,30.2,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,DVC,77.4,79.5,80.3,76.7,80.3,76.8,75.4,69.2,70.8,...,77.4,79.2,75.4,74.9,75.0,78.8,79.7,78.5,79.4,78.5
12,Delhi,94.5,95.7,97.9,99.4,101.9,100.7,98.5,68.6,68.9,...,131.3,121.1,108.2,108.8,110.0,108.8,105.5,104.7,103.3,101.7
13,Essar steel,17.1,15.5,16.2,15.6,15.4,16.8,17.1,8.7,9.9,...,NaN,NaN,NaN,17.2,17.1,16.7,16.9,16.2,16.9,16.9
14,Goa,14.6,14.4,14.1,14.5,14.4,14.9,13.2,9.2,9.2,...,14.5,14.2,13.9,13.5,14.5,14.7,14.1,14.1,14.3,13.8
15,Gujarat,424.5,430.6,428.3,436.2,445.0,443.3,419.0,296.2,299.4,...,461.8,440.9,369.0,426.2,433.3,431.7,438.8,428.6,433.8,418.1
16,HP,31.7,31.2,32.0,32.7,32.7,32.8,29.4,26.6,27.6,...,35.0,35.1,30.4,31.9,33.4,33.6,32.7,30.7,33.0,30.7
17,Haryana,139.2,141.7,138.7,145.0,149.0,146.6,138.2,123.3,128.5,...,236.5,217.1,177.5,150.1,155.5,160.0,153.4,156.7,157.9,147.1
18,J&K,46.5,46.8,46.8,46.3,50.9,48.6,51.8,46.7,47.1,...,47.2,49.0,47.7,48.6,49.5,46.1,46.3,50.1,47.6,50.1
19,Jharkhand,33.9,34.7,34.1,33.2,34.0,33.8,29.8,24.8,24.5,...,39.1,40.2,37.9,33.4,32.7,32.5,35.7,36.6,37.0,36.0
20,Karnataka,271.5,270.9,271.3,277.4,282.9,271.5,250.1,202.6,204.7,...,262.1,254.4,231.9,270.5,269.3,262.1,236.1,213.2,212.7,190.5
21,Kerala,85.0,86.0,80.4,81.2,79.0,73.5,69.8,64.2,64.7,...,78.8,78.9,70.5,78.9,78.0,76.7,73.0,69.6,80.3,76.2
22,MP,257.8,262.7,263.8,257.9,256.9,263.7,269.9,225.2,227.1,...,223.1,193.9,191.3,268.8,257.0,261.5,275.4,278.1,278.0,275.9
23,Maharashtra,611.1,623.3,615.4,611.3,612.0,611.9,590.0,405.2,409.3,...,527.2,519.8,508.6,591.6,598.2,594.2,601.0,609.8,609.7,591.4
24,Manipur,2.6,2.7,2.6,2.6,2.5,2.8,2.5,2.8,2.7,...,2.8,2.7,2.8,2.6,2.6,2.4,2.3,1.9,2.3,2.4
25,Meghalaya,5.1,5.8,6.2,6.5,6.4,6.3,5.5,6.7,6.4,...,5.6,6.0,5.6,5.5,6.2,5.8,4.9,4.7,5.1,4.7
26,Mizoram,1.7,1.7,1.8,1.7,1.8,1.8,1.8,1.8,1.8,...,1.7,1.8,1.7,1.7,1.8,1.7,1.7,1.5,1.7,1.7
27,NER Meghalaya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Nagaland,2.2,2.4,2.2,2.2,2.2,2.2,2.3,2.0,2.1,...,2.5,2.5,3.0,2.4,2.5,1.9,2.3,1.7,2.1,2.1
29,Odisha,108.5,109.3,113.5,112.7,115.0,120.3,125.5,68.5,67.7,...,116.2,113.4,122.4,125.4,120.3,117.3,120.6,116.9,121.6,121.1
30,Pondy,9.1,9.2,9.3,9.3,9.4,9.3,8.1,6.0,6.3,...,10.1,10.1,8.4,8.6,9.0,8.7,8.0,8.8,9.3,8.6
31,Punjab,149.5,142.2,147.1,161.3,160.0,158.9,147.2,105.4,108.2,...,276.5,268.5,196.0,158.5,159.3,165.8,151.5,152.5,161.1,151.4
32,Railways_ER ISTS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Railways_ER ISTS*,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.2,0.2,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Railways_NR ISTS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.6,3.4,3.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Rajasthan,249.4,253.7,254.3,249.6,260.1,262.9,256.4,209.3,211.5,...,307.7,275.9,235.3,263.2,258.5,248.6,258.7,263.0,265.8,264.7
36,Sikkim,1.7,1.8,1.8,1.6,1.3,1.0,1.0,1.6,1.6,...,1.4,1.3,0.9,1.6,1.8,1.7,1.7,1.7,1.4,1.2
37,Tamil Nadu,363.1,367.1,367.6,372.7,372.7,360.1,320.3,288.9,292.5,...,365.2,348.7,314.3,339.2,345.0,336.8,313.2,324.1,335.8,296.9
38,Telangana,265.7,266.0,265.7,267.1,265.0,253.0,254.4,177.8,179.7,...,245.0,254.2,259.1,252.3,254.6,250.5,223.3,239.6,243.7,235.7
39,Tripura,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.1,6.4,5.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,UP,397.5,395.7,405.1,407.8,412.5,416.9,407.2,305.3,310.5,...,476.3,459.3,429.2,424.4,431.7,433.2,421.5,406.6,421.7,422.4
41,Uttarakhand,39.8,40.6,37.5,38.8,40.9,41.6,39.0,38.3,39.2,...,45.8,45.8,39.5,41.7,40.7,41.9,41.2,40.7,38.2,39.9
42,West Bengal,178.1,185.0,185.3,188.2,186.6,186.9,178.2,103.3,111.5,...,203.3,211.6,205.8,186.4,194.6,195.6,193.2,187.1,197.2,186.4
43,Total Consumption,4393.7,4431.5,4423.3,4466.5,4515.1,4471.3,4296.2,3248.3,3300.3,...,4795.5,4654.2,4284.2,4430.8,4464.8,4444.5,4369.4,4346.0,4425.4,4270.2

In [269]:
def count_nan_per_row(df):
    """
    Count NaN values for each row and add as a new column
    """
    df_result = df.copy()
    
    # Count NaN values across all columns for each row
    df_result['NaN_Count'] = df_result.isnull().sum(axis=1)
    
    return df_result

# Apply the function
x = count_nan_per_row(df)

# Display the States column and NaN count
print(x[['States', 'NaN_Count']])

               States  NaN_Count
0              AMNSIL       2163
1      Andhra Pradesh          0
2   Arunachal Pradesh          0
3               Assam          0
4               BALCO       2163
5               Bihar          0
6          Chandigarh          0
7        Chhattisgarh          0
8                  DD        707
9                 DNH        712
10          DNHDDPDCL       1988
11                DVC          0
12              Delhi          0
13        Essar steel        532
14                Goa          0
15            Gujarat          0
16                 HP          0
17            Haryana          0
18                J&K          0
19          Jharkhand          0
20          Karnataka          0
21             Kerala          0
22                 MP          0
23        Maharashtra          0
24            Manipur          0
25          Meghalaya         14
26            Mizoram          0
27      NER Meghalaya       2681
28           Nagaland          0
29             Odisha          0
30              Pondy          0
31             Punjab          0
32   Railways_ER ISTS       2520
33  Railways_ER ISTS*       2359
34   Railways_NR ISTS       2163
35          Rajasthan          0
36             Sikkim          0
37         Tamil Nadu          0
38          Telangana          0
39            Tripura       2359
40                 UP          0
41        Uttarakhand          0
42        West Bengal          0
43  Total Consumption          6

In [270]:
# Apply the function
x = count_nan_per_row(df)

# Display the States column and NaN count
print(x[['States', 'NaN_Count']])

               States  NaN_Count
0              AMNSIL       2163
1      Andhra Pradesh          0
2   Arunachal Pradesh          0
3               Assam          0
4               BALCO       2163
5               Bihar          0
6          Chandigarh          0
7        Chhattisgarh          0
8                  DD        707
9                 DNH        712
10          DNHDDPDCL       1988
11                DVC          0
12              Delhi          0
13        Essar steel        532
14                Goa          0
15            Gujarat          0
16                 HP          0
17            Haryana          0
18                J&K          0
19          Jharkhand          0
20          Karnataka          0
21             Kerala          0
22                 MP          0
23        Maharashtra          0
24            Manipur          0
25          Meghalaya         14
26            Mizoram          0
27      NER Meghalaya       2681
28           Nagaland          0
29             Odisha          0
30              Pondy          0
31             Punjab          0
32   Railways_ER ISTS       2520
33  Railways_ER ISTS*       2359
34   Railways_NR ISTS       2163
35          Rajasthan          0
36             Sikkim          0
37         Tamil Nadu          0
38          Telangana          0
39            Tripura       2359
40                 UP          0
41        Uttarakhand          0
42        West Bengal          0
43  Total Consumption          6

In [271]:
df.drop([0,4,10,27,30,32,33,34],axis=0, inplace=True)

In [272]:
df.set_index('States', inplace=True)

In [273]:
df.head(50)

,04-04-2022,05-04-2022,06-04-2022,07-04-2022,08-04-2022,09-04-2022,10-04-2022,08-01-2018,09-01-2018,10-01-2018,...,15-09-2023,16-09-2023,17-09-2023,11-04-2022,12-04-2022,13-04-2022,14-04-2022,15-04-2022,16-04-2022,17-04-2022
States,,,,,,,,,,,,,,,,,,,,,
Andhra Pradesh,220.8,218.7,205.9,213.1,217.1,211.8,207.4,162.2,165.2,165.6,...,230.9,230.3,226.5,209.4,208.8,209.2,213.0,211.6,210.5,200.7
Arunachal Pradesh,2.2,2.3,2.4,2.4,2.4,2.3,2.3,2.3,2.2,2.2,...,3.0,2.9,3.1,2.4,2.4,2.2,2.2,1.5,2.0,2.1
Assam,23.8,26.3,26.8,27.8,27.9,26.1,22.9,22.8,23.6,23.8,...,50.0,49.1,47.1,23.2,27.8,28.6,22.1,19.8,20.7,21.2
Bihar,114.4,110.1,112.7,119.2,118.9,116.7,110.0,71.5,73.9,74.7,...,147.9,152.5,152.9,114.1,117.3,121.0,122.4,118.8,123.6,125.2
Chandigarh,4.5,4.6,4.6,4.6,4.7,4.6,4.3,3.7,3.8,3.8,...,6.6,6.2,6.0,5.0,5.3,5.5,4.7,4.6,4.6,4.3
Chhattisgarh,123.3,125.8,123.4,122.7,124.8,122.2,120.2,73.3,73.4,73.6,...,92.8,96.5,93.7,120.6,122.6,120.5,123.9,123.7,125.0,123.4
DD,7.5,7.9,8.0,8.0,8.2,8.2,7.4,7.0,7.2,7.3,...,NaN,NaN,NaN,7.7,8.0,8.1,8.0,8.1,8.0,7.3
DNH,18.4,19.6,20.2,19.2,20.3,20.5,20.1,17.3,17.6,17.4,...,NaN,NaN,NaN,20.5,20.5,20.1,20.4,20.2,20.1,19.9
DVC,77.4,79.5,80.3,76.7,80.3,76.8,75.4,69.2,70.8,69.0,...,77.4,79.2,75.4,74.9,75.0,78.8,79.7,78.5,79.4,78.5
Delhi,94.5,95.7,97.9,99.4,101.9,100.7,98.5,68.6,68.9,69.3,...,131.3,121.1,108.2,108.8,110.0,108.8,105.5,104.7,103.3,101.7
Essar steel,17.1,15.5,16.2,15.6,15.4,16.8,17.1,8.7,9.9,8.8,...,NaN,NaN,NaN,17.2,17.1,16.7,16.9,16.2,16.9,16.9
Goa,14.6,14.4,14.1,14.5,14.4,14.9,13.2,9.2,9.2,9.2,...,14.5,14.2,13.9,13.5,14.5,14.7,14.1,14.1,14.3,13.8
Gujarat,424.5,430.6,428.3,436.2,445.0,443.3,419.0,296.2,299.4,302.2,...,461.8,440.9,369.0,426.2,433.3,431.7,438.8,428.6,433.8,418.1
HP,31.7,31.2,32.0,32.7,32.7,32.8,29.4,26.6,27.6,27.9,...,35.0,35.1,30.4,31.9,33.4,33.6,32.7,30.7,33.0,30.7
Haryana,139.2,141.7,138.7,145.0,149.0,146.6,138.2,123.3,128.5,129.9,...,236.5,217.1,177.5,150.1,155.5,160.0,153.4,156.7,157.9,147.1
J&K,46.5,46.8,46.8,46.3,50.9,48.6,51.8,46.7,47.1,45.5,...,47.2,49.0,47.7,48.6,49.5,46.1,46.3,50.1,47.6,50.1
Jharkhand,33.9,34.7,34.1,33.2,34.0,33.8,29.8,24.8,24.5,24.6,...,39.1,40.2,37.9,33.4,32.7,32.5,35.7,36.6,37.0,36.0
Karnataka,271.5,270.9,271.3,277.4,282.9,271.5,250.1,202.6,204.7,206.6,...,262.1,254.4,231.9,270.5,269.3,262.1,236.1,213.2,212.7,190.5
Kerala,85.0,86.0,80.4,81.2,79.0,73.5,69.8,64.2,64.7,66.2,...,78.8,78.9,70.5,78.9,78.0,76.7,73.0,69.6,80.3,76.2
MP,257.8,262.7,263.8,257.9,256.9,263.7,269.9,225.2,227.1,227.0,...,223.1,193.9,191.3,268.8,257.0,261.5,275.4,278.1,278.0,275.9
Maharashtra,611.1,623.3,615.4,611.3,612.0,611.9,590.0,405.2,409.3,413.4,...,527.2,519.8,508.6,591.6,598.2,594.2,601.0,609.8,609.7,591.4
Manipur,2.6,2.7,2.6,2.6,2.5,2.8,2.5,2.8,2.7,2.7,...,2.8,2.7,2.8,2.6,2.6,2.4,2.3,1.9,2.3,2.4
Meghalaya,5.1,5.8,6.2,6.5,6.4,6.3,5.5,6.7,6.4,6.5,...,5.6,6.0,5.6,5.5,6.2,5.8,4.9,4.7,5.1,4.7
Mizoram,1.7,1.7,1.8,1.7,1.8,1.8,1.8,1.8,1.8,1.9,...,1.7,1.8,1.7,1.7,1.8,1.7,1.7,1.5,1.7,1.7
Nagaland,2.2,2.4,2.2,2.2,2.2,2.2,2.3,2.0,2.1,2.0,...,2.5,2.5,3.0,2.4,2.5,1.9,2.3,1.7,2.1,2.1
Odisha,108.5,109.3,113.5,112.7,115.0,120.3,125.5,68.5,67.7,70.2,...,116.2,113.4,122.4,125.4,120.3,117.3,120.6,116.9,121.6,121.1
Punjab,149.5,142.2,147.1,161.3,160.0,158.9,147.2,105.4,108.2,108.7,...,276.5,268.5,196.0,158.5,159.3,165.8,151.5,152.5,161.1,151.4
Rajasthan,249.4,253.7,254.3,249.6,260.1,262.9,256.4,209.3,211.5,216.9,...,307.7,275.9,235.3,263.2,258.5,248.6,258.7,263.0,265.8,264.7
Sikkim,1.7,1.8,1.8,1.6,1.3,1.0,1.0,1.6,1.6,1.8,...,1.4,1.3,0.9,1.6,1.8,1.7,1.7,1.7,1.4,1.2
Tamil Nadu,363.1,367.1,367.6,372.7,372.7,360.1,320.3,288.9,292.5,279.8,...,365.2,348.7,314.3,339.2,345.0,336.8,313.2,324.1,335.8,296.9
Telangana,265.7,266.0,265.7,267.1,265.0,253.0,254.4,177.8,179.7,180.7,...,245.0,254.2,259.1,252.3,254.6,250.5,223.3,239.6,243.7,235.7
Tripura,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.1,6.4,5.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UP,397.5,395.7,405.1,407.8,412.5,416.9,407.2,305.3,310.5,309.9,...,476.3,459.3,429.2,424.4,431.7,433.2,421.5,406.6,421.7,422.4
Uttarakhand,39.8,40.6,37.5,38.8,40.9,41.6,39.0,38.3,39.2,39.9,...,45.8,45.8,39.5,41.7,40.7,41.9,41.2,40.7,38.2,39.9
West Bengal,178.1,185.0,185.3,188.2,186.6,186.9,178.2,103.3,111.5,113.2,...,203.3,211.6,205.8,186.4,194.6,195.6,193.2,187.1,197.2,186.4
Total Consumption,4393.7,4431.5,4423.3,4466.5,4515.1,4471.3,4296.2,3248.3,3300.3,3308.7,...,4795.5,4654.2,4284.2,4430.8,4464.8,4444.5,4369.4,4346.0,4425.4,4270.2

In [274]:
df = df.T
df.head(40)

States,Andhra Pradesh,Arunachal Pradesh,Assam,Bihar,Chandigarh,Chhattisgarh,DD,DNH,DVC,Delhi,...,Punjab,Rajasthan,Sikkim,Tamil Nadu,Telangana,Tripura,UP,Uttarakhand,West Bengal,Total Consumption
04-04-2022,220.8,2.2,23.8,114.4,4.5,123.3,7.5,18.4,77.4,94.5,...,149.5,249.4,1.7,363.1,265.7,NaN,397.5,39.8,178.1,4393.7
05-04-2022,218.7,2.3,26.3,110.1,4.6,125.8,7.9,19.6,79.5,95.7,...,142.2,253.7,1.8,367.1,266.0,NaN,395.7,40.6,185.0,4431.5
06-04-2022,205.9,2.4,26.8,112.7,4.6,123.4,8.0,20.2,80.3,97.9,...,147.1,254.3,1.8,367.6,265.7,NaN,405.1,37.5,185.3,4423.3
07-04-2022,213.1,2.4,27.8,119.2,4.6,122.7,8.0,19.2,76.7,99.4,...,161.3,249.6,1.6,372.7,267.1,NaN,407.8,38.8,188.2,4466.5
08-04-2022,217.1,2.4,27.9,118.9,4.7,124.8,8.2,20.3,80.3,101.9,...,160.0,260.1,1.3,372.7,265.0,NaN,412.5,40.9,186.6,4515.1
09-04-2022,211.8,2.3,26.1,116.7,4.6,122.2,8.2,20.5,76.8,100.7,...,158.9,262.9,1.0,360.1,253.0,NaN,416.9,41.6,186.9,4471.3
10-04-2022,207.4,2.3,22.9,110.0,4.3,120.2,7.4,20.1,75.4,98.5,...,147.2,256.4,1.0,320.3,254.4,NaN,407.2,39.0,178.2,4296.2
08-01-2018,162.2,2.3,22.8,71.5,3.7,73.3,7.0,17.3,69.2,68.6,...,105.4,209.3,1.6,288.9,177.8,NaN,305.3,38.3,103.3,3248.3
09-01-2018,165.2,2.2,23.6,73.9,3.8,73.4,7.2,17.6,70.8,68.9,...,108.2,211.5,1.6,292.5,179.7,NaN,310.5,39.2,111.5,3300.3
10-01-2018,165.6,2.2,23.8,74.7,3.8,73.6,7.3,17.4,69.0,69.3,...,108.7,216.9,1.8,279.8,180.7,NaN,309.9,39.9,113.2,3308.7
11-01-2018,167.3,2.3,22.7,74.6,3.8,73.0,7.3,17.8,69.7,68.5,...,105.6,217.5,1.7,277.7,180.1,NaN,307.9,39.8,112.5,3313.9
12-01-2018,172.6,2.3,24.0,73.4,3.7,74.4,7.4,17.7,70.7,69.3,...,105.9,219.7,1.8,292.4,180.6,NaN,309.2,39.8,113.9,3351.9
13-01-2018,170.0,2.3,23.9,74.0,3.5,78.1,7.5,17.2,70.5,63.5,...,102.5,213.0,1.6,284.2,183.6,NaN,310.6,38.9,112.7,3330.4
14-01-2018,166.9,2.3,22.2,80.9,3.2,72.2,6.3,16.7,69.7,61.7,...,94.0,206.2,1.0,239.9,171.7,NaN,301.5,36.9,104.5,3117.8
10-02-2020,180.7,2.2,22.1,77.5,3.9,73.7,7.0,17.1,65.9,68.5,...,130.1,243.3,1.9,304.3,192.4,NaN,290.4,37.5,119.7,3549.3
11-02-2020,184.5,2.2,22.6,77.6,4.0,73.7,7.4,18.5,66.5,69.5,...,129.2,248.1,1.9,310.0,210.8,NaN,295.5,38.7,120.9,3641.6
12-02-2020,186.4,2.2,22.7,77.1,3.9,78.7,7.3,18.7,66.3,68.8,...,134.2,249.0,1.8,311.9,216.8,NaN,288.0,38.6,123.3,3663.1
13-02-2020,187.8,2.3,23.1,76.1,3.8,80.9,7.4,18.7,65.8,66.8,...,131.3,249.0,1.9,315.1,223.0,NaN,282.1,37.6,122.5,3667.6
14-02-2020,189.0,2.2,23.6,75.6,3.7,82.6,7.4,18.5,63.4,66.8,...,131.4,248.1,2.0,324.0,225.7,NaN,273.9,37.2,121.7,3665.8
15-02-2020,189.7,2.3,22.8,74.8,3.5,83.8,7.3,18.4,64.3,62.6,...,132.6,249.3,2.0,307.8,236.2,NaN,278.7,36.7,120.6,3651.8
16-02-2020,189.7,2.2,21.4,77.4,3.2,83.8,6.8,18.0,64.2,61.1,...,126.9,245.5,1.7,296.6,235.6,NaN,286.6,34.3,115.9,3567.9
06-11-2023,207.4,2.7,27.1,91.1,3.5,94.0,NaN,NaN,70.9,77.3,...,135.2,315.8,1.3,301.8,210.2,4.4,331.5,38.6,153.7,4191.1
07-11-2023,206.8,2.4,29.0,88.3,3.6,92.5,NaN,NaN,69.9,77.9,...,136.4,324.0,1.3,304.8,204.2,4.4,335.7,39.6,151.9,4201.0
08-11-2023,207.1,2.5,29.9,86.9,3.6,91.1,NaN,NaN,68.9,77.9,...,139.3,320.2,1.3,302.6,198.6,4.2,334.3,39.8,149.6,4199.4
09-11-2023,202.8,2.6,29.6,86.0,3.6,93.0,NaN,NaN,67.1,77.7,...,137.4,313.8,1.4,301.6,202.3,4.2,333.8,39.9,150.0,4159.8
10-11-2023,204.5,2.8,29.4,90.3,3.6,93.6,NaN,NaN,70.5,75.8,...,126.7,304.3,1.4,299.7,208.4,4.2,335.3,40.7,149.9,4116.1
11-11-2023,202.2,2.7,29.6,88.9,3.2,91.7,NaN,NaN,71.0,68.6,...,123.2,291.8,1.3,265.0,204.8,4.2,328.0,36.1,147.1,3939.0
12-11-2023,198.0,2.7,26.9,90.5,3.0,86.1,NaN,NaN,70.7,59.6,...,95.6,270.8,1.1,212.3,198.9,4.3,316.8,28.6,132.6,3581.9
13-08-2018,158.0,2.2,30.5,90.1,5.3,83.6,7.5,18.3,65.2,114.9,...,224.7,238.4,1.1,294.1,168.2,NaN,350.5,34.4,168.4,3661.7
14-08-2018,158.4,2.2,34.6,95.3,5.6,86.4,7.5,18.4,65.0,117.3,...,243.8,242.2,1.2,282.5,179.8,NaN,360.2,38.2,176.1,3750.1
15-08-2018,150.7,2.2,31.0,94.8,5.0,84.0,5.0,14.9,65.0,102.7,...,215.9,238.7,1.5,254.2,175.8,NaN,364.7,33.9,159.1,3505.8
16-08-2018,149.8,2.1,31.9,91.6,5.8,81.4,6.4,16.7,64.5,116.6,...,233.5,231.1,1.0,272.1,157.0,NaN,354.1,40.0,165.4,3532.8
17-08-2018,158.3,2.3,34.0,98.0,5.3,88.1,7.5,17.7,67.6,121.0,...,238.0,231.5,1.2,294.6,168.5,NaN,385.3,42.4,180.9,3619.9
18-08-2018,161.6,2.3,35.0,95.9,5.2,88.2,7.7,17.9,67.9,117.9,...,224.9,226.2,1.1,289.6,177.3,NaN,393.5,41.7,185.0,3625.8
19-08-2018,158.2,2.3,35.6,99.4,5.0,82.9,7.1,17.9,67.9,108.0,...,220.7,217.2,0.8,284.4,163.2,NaN,382.5,39.8,170.9,3507.1
02-11-2020,185.3,2.0,28.7,82.4,3.0,75.5,7.2,18.1,63.1,63.4,...,107.4,241.3,1.4,317.3,153.0,NaN,271.5,34.9,146.1,3466.5
03-11-2020,190.9,2.0,29.4,74.2,3.0,75.1,7.6,18.3,64.1,64.7,...,107.4,246.6,1.4,328.4,153.1,NaN,270.0,35.9,142.9,3491.6
04-11-2020,183.8,1.9,27.5,69.8,3.0,73.4,7.7,18.1,63.5,64.7,...,107.3,244.8,1.4,326.7,149.5,NaN,269.6,35.6,126.2,3459.1
05-11-2020,185.8,1.9,26.3,70.6,3.0,71.9,9.0,18.1,61.5,62.8,...,109.2,245.2,1.4,301.7,149.2,NaN,264.8,34.0,119.0,3407.6
06-11-2020,179.0,2.1,26.0,68.8,3.0,72.7,8.9,18.0,63.4,65.0,...,112.1,248.4,1.5,294.6,150.1,NaN,283.9,35.9,116.9,3432.1

In [276]:
df.to_csv('/Users/aryankhurana/Electricity-Forecasting-Indian-States/clean_data.csv')

In [277]:
df = pd.read_csv('/Users/aryankhurana/Electricity-Forecasting-Indian-States/clean_data.csv')
df.head(50)

,Dates,Andhra Pradesh,Arunachal Pradesh,Assam,Bihar,Chandigarh,Chhattisgarh,DD,DNH,DVC,...,Punjab,Rajasthan,Sikkim,Tamil Nadu,Telangana,Tripura,UP,Uttarakhand,West Bengal,Total Consumption
0,04-04-2022,220.8,2.2,23.8,114.4,4.5,123.3,7.5,18.4,77.4,...,149.5,249.4,1.7,363.1,265.7,NaN,397.5,39.8,178.1,4393.7
1,05-04-2022,218.7,2.3,26.3,110.1,4.6,125.8,7.9,19.6,79.5,...,142.2,253.7,1.8,367.1,266.0,NaN,395.7,40.6,185.0,4431.5
2,06-04-2022,205.9,2.4,26.8,112.7,4.6,123.4,8.0,20.2,80.3,...,147.1,254.3,1.8,367.6,265.7,NaN,405.1,37.5,185.3,4423.3
3,07-04-2022,213.1,2.4,27.8,119.2,4.6,122.7,8.0,19.2,76.7,...,161.3,249.6,1.6,372.7,267.1,NaN,407.8,38.8,188.2,4466.5
4,08-04-2022,217.1,2.4,27.9,118.9,4.7,124.8,8.2,20.3,80.3,...,160.0,260.1,1.3,372.7,265.0,NaN,412.5,40.9,186.6,4515.1
5,09-04-2022,211.8,2.3,26.1,116.7,4.6,122.2,8.2,20.5,76.8,...,158.9,262.9,1.0,360.1,253.0,NaN,416.9,41.6,186.9,4471.3
6,10-04-2022,207.4,2.3,22.9,110.0,4.3,120.2,7.4,20.1,75.4,...,147.2,256.4,1.0,320.3,254.4,NaN,407.2,39.0,178.2,4296.2
7,08-01-2018,162.2,2.3,22.8,71.5,3.7,73.3,7.0,17.3,69.2,...,105.4,209.3,1.6,288.9,177.8,NaN,305.3,38.3,103.3,3248.3
8,09-01-2018,165.2,2.2,23.6,73.9,3.8,73.4,7.2,17.6,70.8,...,108.2,211.5,1.6,292.5,179.7,NaN,310.5,39.2,111.5,3300.3
9,10-01-2018,165.6,2.2,23.8,74.7,3.8,73.6,7.3,17.4,69.0,...,108.7,216.9,1.8,279.8,180.7,NaN,309.9,39.9,113.2,3308.7
10,11-01-2018,167.3,2.3,22.7,74.6,3.8,73.0,7.3,17.8,69.7,...,105.6,217.5,1.7,277.7,180.1,NaN,307.9,39.8,112.5,3313.9
11,12-01-2018,172.6,2.3,24.0,73.4,3.7,74.4,7.4,17.7,70.7,...,105.9,219.7,1.8,292.4,180.6,NaN,309.2,39.8,113.9,3351.9
12,13-01-2018,170.0,2.3,23.9,74.0,3.5,78.1,7.5,17.2,70.5,...,102.5,213.0,1.6,284.2,183.6,NaN,310.6,38.9,112.7,3330.4
13,14-01-2018,166.9,2.3,22.2,80.9,3.2,72.2,6.3,16.7,69.7,...,94.0,206.2,1.0,239.9,171.7,NaN,301.5,36.9,104.5,3117.8
14,10-02-2020,180.7,2.2,22.1,77.5,3.9,73.7,7.0,17.1,65.9,...,130.1,243.3,1.9,304.3,192.4,NaN,290.4,37.5,119.7,3549.3
15,11-02-2020,184.5,2.2,22.6,77.6,4.0,73.7,7.4,18.5,66.5,...,129.2,248.1,1.9,310.0,210.8,NaN,295.5,38.7,120.9,3641.6
16,12-02-2020,186.4,2.2,22.7,77.1,3.9,78.7,7.3,18.7,66.3,...,134.2,249.0,1.8,311.9,216.8,NaN,288.0,38.6,123.3,3663.1
17,13-02-2020,187.8,2.3,23.1,76.1,3.8,80.9,7.4,18.7,65.8,...,131.3,249.0,1.9,315.1,223.0,NaN,282.1,37.6,122.5,3667.6
18,14-02-2020,189.0,2.2,23.6,75.6,3.7,82.6,7.4,18.5,63.4,...,131.4,248.1,2.0,324.0,225.7,NaN,273.9,37.2,121.7,3665.8
19,15-02-2020,189.7,2.3,22.8,74.8,3.5,83.8,7.3,18.4,64.3,...,132.6,249.3,2.0,307.8,236.2,NaN,278.7,36.7,120.6,3651.8
20,16-02-2020,189.7,2.2,21.4,77.4,3.2,83.8,6.8,18.0,64.2,...,126.9,245.5,1.7,296.6,235.6,NaN,286.6,34.3,115.9,3567.9
21,06-11-2023,207.4,2.7,27.1,91.1,3.5,94.0,NaN,NaN,70.9,...,135.2,315.8,1.3,301.8,210.2,4.4,331.5,38.6,153.7,4191.1
22,07-11-2023,206.8,2.4,29.0,88.3,3.6,92.5,NaN,NaN,69.9,...,136.4,324.0,1.3,304.8,204.2,4.4,335.7,39.6,151.9,4201.0
23,08-11-2023,207.1,2.5,29.9,86.9,3.6,91.1,NaN,NaN,68.9,...,139.3,320.2,1.3,302.6,198.6,4.2,334.3,39.8,149.6,4199.4
24,09-11-2023,202.8,2.6,29.6,86.0,3.6,93.0,NaN,NaN,67.1,...,137.4,313.8,1.4,301.6,202.3,4.2,333.8,39.9,150.0,4159.8
25,10-11-2023,204.5,2.8,29.4,90.3,3.6,93.6,NaN,NaN,70.5,...,126.7,304.3,1.4,299.7,208.4,4.2,335.3,40.7,149.9,4116.1
26,11-11-2023,202.2,2.7,29.6,88.9,3.2,91.7,NaN,NaN,71.0,...,123.2,291.8,1.3,265.0,204.8,4.2,328.0,36.1,147.1,3939.0
27,12-11-2023,198.0,2.7,26.9,90.5,3.0,86.1,NaN,NaN,70.7,...,95.6,270.8,1.1,212.3,198.9,4.3,316.8,28.6,132.6,3581.9
28,13-08-2018,158.0,2.2,30.5,90.1,5.3,83.6,7.5,18.3,65.2,...,224.7,238.4,1.1,294.1,168.2,NaN,350.5,34.4,168.4,3661.7
29,14-08-2018,158.4,2.2,34.6,95.3,5.6,86.4,7.5,18.4,65.0,...,243.8,242.2,1.2,282.5,179.8,NaN,360.2,38.2,176.1,3750.1
30,15-08-2018,150.7,2.2,31.0,94.8,5.0,84.0,5.0,14.9,65.0,...,215.9,238.7,1.5,254.2,175.8,NaN,364.7,33.9,159.1,3505.8
31,16-08-2018,149.8,2.1,31.9,91.6,5.8,81.4,6.4,16.7,64.5,...,233.5,231.1,1.0,272.1,157.0,NaN,354.1,40.0,165.4,3532.8
32,17-08-2018,158.3,2.3,34.0,98.0,5.3,88.1,7.5,17.7,67.6,...,238.0,231.5,1.2,294.6,168.5,NaN,385.3,42.4,180.9,3619.9
33,18-08-2018,161.6,2.3,35.0,95.9,5.2,88.2,7.7,17.9,67.9,...,224.9,226.2,1.1,289.6,177.3,NaN,393.5,41.7,185.0,3625.8
34,19-08-2018,158.2,2.3,35.6,99.4,5.0,82.9,7.1,17.9,67.9,...,220.7,217.2,0.8,284.4,163.2,NaN,382.5,39.8,170.9,3507.1
35,02-11-2020,185.3,2.0,28.7,82.4,3.0,75.5,7.2,18.1,63.1,...,107.4,241.3,1.4,317.3,153.0,NaN,271.5,34.9,146.1,3466.5
36,03-11-2020,190.9,2.0,29.4,74.2,3.0,75.1,7.6,18.3,64.1,...,107.4,246.6,1.4,328.4,153.1,NaN,270.0,35.9,142.9,3491.6
37,04-11-2020,183.8,1.9,27.5,69.8,3.0,73.4,7.7,18.1,63.5,...,107.3,244.8,1.4,326.7,149.5,NaN,269.6,35.6,126.2,3459.1
38,05-11-2020,185.8,1.9,26.3,70.6,3.0,71.9,9.0,18.1,61.5,...,109.2,245.2,1.4,301.7,149.2,NaN,264.8,34.0,119.0,3407.6
39,06-11-2020,179.0,2.1,26.0,68.8,3.0,72.7,8.9,18.0,63.4,...,112.1,248.4,1.5,294.6,150.1,NaN,283.9,35.9,116.9,3432.1
40,07-11-2020,174.2,2.1,25.7,68.7,3.0,71.7,7.6,18.0,63.3,...,111.7,248.5,1.5,296.2,147.3,NaN,279.2,35.0,111.7,3423.7
41,08-11-2020,169.2,2.0,23.9,70.6,2.7,71.2,6.8,17.3,62.5,...,106.8,247.8,1.3,269.7,137.1,NaN,277.1,33.9,105.2,3295.4
42,05-09-2016,147.4,2.0,27.5,71.5,6.0,79.1,6.0,16.3,60.9,...,210.2,173.3,1.1,257.8,154.2,NaN,319.2,37.4,138.7,3176.7
43,06-09-2016,154.9,2.2,30.0,66.3,6.1,80.8,6.7,16.7,58.2,...,215.5,184.6,1.1,285.4,163.8,NaN,324.7,35.0,134.1,3326.0
44,07-09-2016,160.8,2.0,29.3,67.0,6.1,83.0,7.0,17.0,58.8,...,230.7,188.5,1.1,296.7,169.9,NaN,326.1,39.8,132.7,3421.1
45,08-09-2016,167.4,1.9,29.8,67.3,6.0,83.4,7.0,17.3,61.5,...,229.4,193.0,1.3,300.6,173.3,NaN,329.6,40.7,144.0,3508.4
46,09-09-2016,169.9,2.0,31.0,71.8,5.9,78.8,6.9,17.2,62.1,...,231.8,203.1,1.2,303.8,173.8,NaN,329.8,40.4,147.0,3535.0
47,10-09-2016,160.8,2.0,29.8,68.1,5.7,75.3,6.6,17.2,61.9,...,227.8,203.8,1.2,302.9,161.2,NaN,334.0,45.8,148.9,3535.7
48,11-09-2016,150.0,1.9,29.1,68.8,5.2,73.3,6.8,17.0,62.0,...,216.6,203.4,1.0,275.9,141.5,NaN,335.8,38.3,142.6,3390.9
49,16-04-2018,183.5,2.1,24.2,85.5,3.9,83.7,7.1,17.6,73.5,...,112.7,184.9,1.4,332.2,173.5,NaN,311.1,33.7,166.1,3522.5

In [278]:
from datetime import datetime

def convert_date_format(df):
    """
    Convert date format from dd-mm-yyyy to yyyy-mm-dd
    """
    df_result = df.copy()
    
    # Function to parse and convert date format
    def parse_date(date_str):
        try:
            # Parse the date string (assuming it's in dd-mm-yyyy format)
            # From your screenshot, it looks like: 04-04-2022, 05-04-2022, etc.
            date_obj = pd.to_datetime(date_str, format='%d-%m-%Y')
            # Convert to yyyy-mm-dd format
            return date_obj.strftime('%Y-%m-%d')
        except:
            # If parsing fails, return original value
            return date_str
    
    # Apply the conversion to the dates column
    df_result['Dates'] = df_result['Dates'].apply(parse_date)
    
    return df_result

# Apply the function
df = convert_date_format(df)
df.head(50)

,Dates,Andhra Pradesh,Arunachal Pradesh,Assam,Bihar,Chandigarh,Chhattisgarh,DD,DNH,DVC,...,Punjab,Rajasthan,Sikkim,Tamil Nadu,Telangana,Tripura,UP,Uttarakhand,West Bengal,Total Consumption
0,2022-04-04,220.8,2.2,23.8,114.4,4.5,123.3,7.5,18.4,77.4,...,149.5,249.4,1.7,363.1,265.7,NaN,397.5,39.8,178.1,4393.7
1,2022-04-05,218.7,2.3,26.3,110.1,4.6,125.8,7.9,19.6,79.5,...,142.2,253.7,1.8,367.1,266.0,NaN,395.7,40.6,185.0,4431.5
2,2022-04-06,205.9,2.4,26.8,112.7,4.6,123.4,8.0,20.2,80.3,...,147.1,254.3,1.8,367.6,265.7,NaN,405.1,37.5,185.3,4423.3
3,2022-04-07,213.1,2.4,27.8,119.2,4.6,122.7,8.0,19.2,76.7,...,161.3,249.6,1.6,372.7,267.1,NaN,407.8,38.8,188.2,4466.5
4,2022-04-08,217.1,2.4,27.9,118.9,4.7,124.8,8.2,20.3,80.3,...,160.0,260.1,1.3,372.7,265.0,NaN,412.5,40.9,186.6,4515.1
5,2022-04-09,211.8,2.3,26.1,116.7,4.6,122.2,8.2,20.5,76.8,...,158.9,262.9,1.0,360.1,253.0,NaN,416.9,41.6,186.9,4471.3
6,2022-04-10,207.4,2.3,22.9,110.0,4.3,120.2,7.4,20.1,75.4,...,147.2,256.4,1.0,320.3,254.4,NaN,407.2,39.0,178.2,4296.2
7,2018-01-08,162.2,2.3,22.8,71.5,3.7,73.3,7.0,17.3,69.2,...,105.4,209.3,1.6,288.9,177.8,NaN,305.3,38.3,103.3,3248.3
8,2018-01-09,165.2,2.2,23.6,73.9,3.8,73.4,7.2,17.6,70.8,...,108.2,211.5,1.6,292.5,179.7,NaN,310.5,39.2,111.5,3300.3
9,2018-01-10,165.6,2.2,23.8,74.7,3.8,73.6,7.3,17.4,69.0,...,108.7,216.9,1.8,279.8,180.7,NaN,309.9,39.9,113.2,3308.7
10,2018-01-11,167.3,2.3,22.7,74.6,3.8,73.0,7.3,17.8,69.7,...,105.6,217.5,1.7,277.7,180.1,NaN,307.9,39.8,112.5,3313.9
11,2018-01-12,172.6,2.3,24.0,73.4,3.7,74.4,7.4,17.7,70.7,...,105.9,219.7,1.8,292.4,180.6,NaN,309.2,39.8,113.9,3351.9
12,2018-01-13,170.0,2.3,23.9,74.0,3.5,78.1,7.5,17.2,70.5,...,102.5,213.0,1.6,284.2,183.6,NaN,310.6,38.9,112.7,3330.4
13,2018-01-14,166.9,2.3,22.2,80.9,3.2,72.2,6.3,16.7,69.7,...,94.0,206.2,1.0,239.9,171.7,NaN,301.5,36.9,104.5,3117.8
14,2020-02-10,180.7,2.2,22.1,77.5,3.9,73.7,7.0,17.1,65.9,...,130.1,243.3,1.9,304.3,192.4,NaN,290.4,37.5,119.7,3549.3
15,2020-02-11,184.5,2.2,22.6,77.6,4.0,73.7,7.4,18.5,66.5,...,129.2,248.1,1.9,310.0,210.8,NaN,295.5,38.7,120.9,3641.6
16,2020-02-12,186.4,2.2,22.7,77.1,3.9,78.7,7.3,18.7,66.3,...,134.2,249.0,1.8,311.9,216.8,NaN,288.0,38.6,123.3,3663.1
17,2020-02-13,187.8,2.3,23.1,76.1,3.8,80.9,7.4,18.7,65.8,...,131.3,249.0,1.9,315.1,223.0,NaN,282.1,37.6,122.5,3667.6
18,2020-02-14,189.0,2.2,23.6,75.6,3.7,82.6,7.4,18.5,63.4,...,131.4,248.1,2.0,324.0,225.7,NaN,273.9,37.2,121.7,3665.8
19,2020-02-15,189.7,2.3,22.8,74.8,3.5,83.8,7.3,18.4,64.3,...,132.6,249.3,2.0,307.8,236.2,NaN,278.7,36.7,120.6,3651.8
20,2020-02-16,189.7,2.2,21.4,77.4,3.2,83.8,6.8,18.0,64.2,...,126.9,245.5,1.7,296.6,235.6,NaN,286.6,34.3,115.9,3567.9
21,2023-11-06,207.4,2.7,27.1,91.1,3.5,94.0,NaN,NaN,70.9,...,135.2,315.8,1.3,301.8,210.2,4.4,331.5,38.6,153.7,4191.1
22,2023-11-07,206.8,2.4,29.0,88.3,3.6,92.5,NaN,NaN,69.9,...,136.4,324.0,1.3,304.8,204.2,4.4,335.7,39.6,151.9,4201.0
23,2023-11-08,207.1,2.5,29.9,86.9,3.6,91.1,NaN,NaN,68.9,...,139.3,320.2,1.3,302.6,198.6,4.2,334.3,39.8,149.6,4199.4
24,2023-11-09,202.8,2.6,29.6,86.0,3.6,93.0,NaN,NaN,67.1,...,137.4,313.8,1.4,301.6,202.3,4.2,333.8,39.9,150.0,4159.8
25,2023-11-10,204.5,2.8,29.4,90.3,3.6,93.6,NaN,NaN,70.5,...,126.7,304.3,1.4,299.7,208.4,4.2,335.3,40.7,149.9,4116.1
26,2023-11-11,202.2,2.7,29.6,88.9,3.2,91.7,NaN,NaN,71.0,...,123.2,291.8,1.3,265.0,204.8,4.2,328.0,36.1,147.1,3939.0
27,2023-11-12,198.0,2.7,26.9,90.5,3.0,86.1,NaN,NaN,70.7,...,95.6,270.8,1.1,212.3,198.9,4.3,316.8,28.6,132.6,3581.9
28,2018-08-13,158.0,2.2,30.5,90.1,5.3,83.6,7.5,18.3,65.2,...,224.7,238.4,1.1,294.1,168.2,NaN,350.5,34.4,168.4,3661.7
29,2018-08-14,158.4,2.2,34.6,95.3,5.6,86.4,7.5,18.4,65.0,...,243.8,242.2,1.2,282.5,179.8,NaN,360.2,38.2,176.1,3750.1
30,2018-08-15,150.7,2.2,31.0,94.8,5.0,84.0,5.0,14.9,65.0,...,215.9,238.7,1.5,254.2,175.8,NaN,364.7,33.9,159.1,3505.8
31,2018-08-16,149.8,2.1,31.9,91.6,5.8,81.4,6.4,16.7,64.5,...,233.5,231.1,1.0,272.1,157.0,NaN,354.1,40.0,165.4,3532.8
32,2018-08-17,158.3,2.3,34.0,98.0,5.3,88.1,7.5,17.7,67.6,...,238.0,231.5,1.2,294.6,168.5,NaN,385.3,42.4,180.9,3619.9
33,2018-08-18,161.6,2.3,35.0,95.9,5.2,88.2,7.7,17.9,67.9,...,224.9,226.2,1.1,289.6,177.3,NaN,393.5,41.7,185.0,3625.8
34,2018-08-19,158.2,2.3,35.6,99.4,5.0,82.9,7.1,17.9,67.9,...,220.7,217.2,0.8,284.4,163.2,NaN,382.5,39.8,170.9,3507.1
35,2020-11-02,185.3,2.0,28.7,82.4,3.0,75.5,7.2,18.1,63.1,...,107.4,241.3,1.4,317.3,153.0,NaN,271.5,34.9,146.1,3466.5
36,2020-11-03,190.9,2.0,29.4,74.2,3.0,75.1,7.6,18.3,64.1,...,107.4,246.6,1.4,328.4,153.1,NaN,270.0,35.9,142.9,3491.6
37,2020-11-04,183.8,1.9,27.5,69.8,3.0,73.4,7.7,18.1,63.5,...,107.3,244.8,1.4,326.7,149.5,NaN,269.6,35.6,126.2,3459.1
38,2020-11-05,185.8,1.9,26.3,70.6,3.0,71.9,9.0,18.1,61.5,...,109.2,245.2,1.4,301.7,149.2,NaN,264.8,34.0,119.0,3407.6
39,2020-11-06,179.0,2.1,26.0,68.8,3.0,72.7,8.9,18.0,63.4,...,112.1,248.4,1.5,294.6,150.1,NaN,283.9,35.9,116.9,3432.1
40,2020-11-07,174.2,2.1,25.7,68.7,3.0,71.7,7.6,18.0,63.3,...,111.7,248.5,1.5,296.2,147.3,NaN,279.2,35.0,111.7,3423.7
41,2020-11-08,169.2,2.0,23.9,70.6,2.7,71.2,6.8,17.3,62.5,...,106.8,247.8,1.3,269.7,137.1,NaN,277.1,33.9,105.2,3295.4
42,2016-09-05,147.4,2.0,27.5,71.5,6.0,79.1,6.0,16.3,60.9,...,210.2,173.3,1.1,257.8,154.2,NaN,319.2,37.4,138.7,3176.7
43,2016-09-06,154.9,2.2,30.0,66.3,6.1,80.8,6.7,16.7,58.2,...,215.5,184.6,1.1,285.4,163.8,NaN,324.7,35.0,134.1,3326.0
44,2016-09-07,160.8,2.0,29.3,67.0,6.1,83.0,7.0,17.0,58.8,...,230.7,188.5,1.1,296.7,169.9,NaN,326.1,39.8,132.7,3421.1
45,2016-09-08,167.4,1.9,29.8,67.3,6.0,83.4,7.0,17.3,61.5,...,229.4,193.0,1.3,300.6,173.3,NaN,329.6,40.7,144.0,3508.4
46,2016-09-09,169.9,2.0,31.0,71.8,5.9,78.8,6.9,17.2,62.1,...,231.8,203.1,1.2,303.8,173.8,NaN,329.8,40.4,147.0,3535.0
47,2016-09-10,160.8,2.0,29.8,68.1,5.7,75.3,6.6,17.2,61.9,...,227.8,203.8,1.2,302.9,161.2,NaN,334.0,45.8,148.9,3535.7
48,2016-09-11,150.0,1.9,29.1,68.8,5.2,73.3,6.8,17.0,62.0,...,216.6,203.4,1.0,275.9,141.5,NaN,335.8,38.3,142.6,3390.9
49,2018-04-16,183.5,2.1,24.2,85.5,3.9,83.7,7.1,17.6,73.5,...,112.7,184.9,1.4,332.2,173.5,NaN,311.1,33.7,166.1,3522.5

In [279]:
df.to_csv('/Users/aryankhurana/Electricity-Forecasting-Indian-States/clean_data.csv')

--------------------------------------------------------------------------------------------------------------------------------------------

In [297]:
data = pd.read_csv('/Users/aryankhurana/Electricity-Forecasting-Indian-States/data_clean.csv')
data.head(5)

,Unnamed: 0,Dates,Andhra Pradesh,Arunachal Pradesh,Assam,Bihar,Chandigarh,Chhattisgarh,DD,Delhi,...,Pondy,Punjab,Rajasthan,Sikkim,Tamil Nadu,Telangana,Tripura,UP,Uttarakhand,West Bengal
0,0,2013-01-06,251.5,1.6,21.3,40.9,3.8,60.3,5.8,66.0,...,5.6,95.2,192.0,1.7,254.5,127.6,2.6,225.0,33.6,107.5
1,1,2013-01-07,257.9,1.7,21.2,39.6,3.8,64.3,5.8,67.2,...,5.5,92.8,192.9,1.8,262.3,129.2,2.6,219.1,34.2,106.6
2,2,2013-01-08,265.1,1.6,20.4,39.2,3.9,63.0,5.9,66.7,...,5.8,93.9,197.1,1.8,256.6,131.9,2.1,238.7,33.9,103.9
3,3,2013-01-09,261.0,1.6,21.4,39.5,3.7,65.0,5.8,67.4,...,5.9,90.1,197.6,1.9,254.6,135.0,2.7,229.1,32.7,105.7
4,4,2013-01-10,260.0,1.6,21.1,39.7,3.8,66.5,5.9,67.8,...,5.9,93.5,199.9,1.9,255.3,130.0,3.2,224.5,35.4,105.3

In [298]:
data.drop('Unnamed: 0', axis=1, inplace=True)
data.head(5)

,Dates,Andhra Pradesh,Arunachal Pradesh,Assam,Bihar,Chandigarh,Chhattisgarh,DD,Delhi,DNH,...,Pondy,Punjab,Rajasthan,Sikkim,Tamil Nadu,Telangana,Tripura,UP,Uttarakhand,West Bengal
0,2013-01-06,251.5,1.6,21.3,40.9,3.8,60.3,5.8,66.0,15.0,...,5.6,95.2,192.0,1.7,254.5,127.6,2.6,225.0,33.6,107.5
1,2013-01-07,257.9,1.7,21.2,39.6,3.8,64.3,5.8,67.2,15.1,...,5.5,92.8,192.9,1.8,262.3,129.2,2.6,219.1,34.2,106.6
2,2013-01-08,265.1,1.6,20.4,39.2,3.9,63.0,5.9,66.7,15.2,...,5.8,93.9,197.1,1.8,256.6,131.9,2.1,238.7,33.9,103.9
3,2013-01-09,261.0,1.6,21.4,39.5,3.7,65.0,5.8,67.4,15.2,...,5.9,90.1,197.6,1.9,254.6,135.0,2.7,229.1,32.7,105.7
4,2013-01-10,260.0,1.6,21.1,39.7,3.8,66.5,5.9,67.8,14.9,...,5.9,93.5,199.9,1.9,255.3,130.0,3.2,224.5,35.4,105.3

In [300]:
data['Total Consumption'] = data.iloc[:, 1:].sum(axis=1)
data.head(5)

,Dates,Andhra Pradesh,Arunachal Pradesh,Assam,Bihar,Chandigarh,Chhattisgarh,DD,Delhi,DNH,...,Punjab,Rajasthan,Sikkim,Tamil Nadu,Telangana,Tripura,UP,Uttarakhand,West Bengal,Total Consumption
0,2013-01-06,251.5,1.6,21.3,40.9,3.8,60.3,5.8,66.0,15.0,...,95.2,192.0,1.7,254.5,127.6,2.6,225.0,33.6,107.5,2845.7
1,2013-01-07,257.9,1.7,21.2,39.6,3.8,64.3,5.8,67.2,15.1,...,92.8,192.9,1.8,262.3,129.2,2.6,219.1,34.2,106.6,2876.7
2,2013-01-08,265.1,1.6,20.4,39.2,3.9,63.0,5.9,66.7,15.2,...,93.9,197.1,1.8,256.6,131.9,2.1,238.7,33.9,103.9,2923.0
3,2013-01-09,261.0,1.6,21.4,39.5,3.7,65.0,5.8,67.4,15.2,...,90.1,197.6,1.9,254.6,135.0,2.7,229.1,32.7,105.7,2912.1
4,2013-01-10,260.0,1.6,21.1,39.7,3.8,66.5,5.9,67.8,14.9,...,93.5,199.9,1.9,255.3,130.0,3.2,224.5,35.4,105.3,2920.8

In [301]:
df.head(5)

,Dates,Andhra Pradesh,Arunachal Pradesh,Assam,Bihar,Chandigarh,Chhattisgarh,DD,DNH,DVC,...,Punjab,Rajasthan,Sikkim,Tamil Nadu,Telangana,Tripura,UP,Uttarakhand,West Bengal,Total Consumption
0,2022-04-04,220.8,2.2,23.8,114.4,4.5,123.3,7.5,18.4,77.4,...,149.5,249.4,1.7,363.1,265.7,NaN,397.5,39.8,178.1,4393.7
1,2022-04-05,218.7,2.3,26.3,110.1,4.6,125.8,7.9,19.6,79.5,...,142.2,253.7,1.8,367.1,266.0,NaN,395.7,40.6,185.0,4431.5
2,2022-04-06,205.9,2.4,26.8,112.7,4.6,123.4,8.0,20.2,80.3,...,147.1,254.3,1.8,367.6,265.7,NaN,405.1,37.5,185.3,4423.3
3,2022-04-07,213.1,2.4,27.8,119.2,4.6,122.7,8.0,19.2,76.7,...,161.3,249.6,1.6,372.7,267.1,NaN,407.8,38.8,188.2,4466.5
4,2022-04-08,217.1,2.4,27.9,118.9,4.7,124.8,8.2,20.3,80.3,...,160.0,260.1,1.3,372.7,265.0,NaN,412.5,40.9,186.6,4515.1

In [304]:
combined_df = pd.concat([data, df], ignore_index=True)

In [305]:
combined_df.head(500)

,Dates,Andhra Pradesh,Arunachal Pradesh,Assam,Bihar,Chandigarh,Chhattisgarh,DD,Delhi,DNH,...,Punjab,Rajasthan,Sikkim,Tamil Nadu,Telangana,Tripura,UP,Uttarakhand,West Bengal,Total Consumption
0,2013-01-06,251.5,1.6,21.3,40.9,3.8,60.3,5.8,66.0,15.0,...,95.2,192.0,1.7,254.5,127.6,2.6,225.0,33.6,107.5,2845.7
1,2013-01-07,257.9,1.7,21.2,39.6,3.8,64.3,5.8,67.2,15.1,...,92.8,192.9,1.8,262.3,129.2,2.6,219.1,34.2,106.6,2876.7
2,2013-01-08,265.1,1.6,20.4,39.2,3.9,63.0,5.9,66.7,15.2,...,93.9,197.1,1.8,256.6,131.9,2.1,238.7,33.9,103.9,2923.0
3,2013-01-09,261.0,1.6,21.4,39.5,3.7,65.0,5.8,67.4,15.2,...,90.1,197.6,1.9,254.6,135.0,2.7,229.1,32.7,105.7,2912.1
4,2013-01-10,260.0,1.6,21.1,39.7,3.8,66.5,5.9,67.8,14.9,...,93.5,199.9,1.9,255.3,130.0,3.2,224.5,35.4,105.3,2920.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,2015-05-03,135.4,1.2,19.8,56.6,4.0,76.8,6.2,81.9,16.2,...,117.5,183.7,1.1,258.6,121.6,3.0,248.0,32.4,122.3,2910.8
496,2015-05-04,142.1,1.2,19.3,55.3,4.7,76.1,6.4,86.1,16.4,...,124.1,185.0,1.1,271.4,124.4,2.9,263.4,33.7,124.1,3006.5
497,2015-05-05,142.9,1.1,19.0,55.3,4.9,79.9,6.4,92.5,16.1,...,126.6,186.1,1.4,279.9,119.0,3.2,260.7,34.5,141.9,3031.3
498,2015-05-06,144.4,1.0,21.9,59.1,5.2,79.6,6.2,95.2,16.3,...,129.6,182.8,1.4,282.2,122.3,2.3,269.9,36.2,145.8,3079.8
499,2015-05-07,142.9,1.2,20.1,60.8,5.4,79.6,6.5,97.4,16.2,...,125.8,184.1,1.2,286.6,125.8,2.8,270.1,36.9,149.2,3113.2

In [ ]:
combined_df = combined_df.drop_duplicates()

In [307]:
# Sort by Dates column
combined_df = combined_df.sort_values('Dates')

In [308]:
combined_df = combined_df.reset_index(drop=True)
combined_df.head(500)

,Dates,Andhra Pradesh,Arunachal Pradesh,Assam,Bihar,Chandigarh,Chhattisgarh,DD,Delhi,DNH,...,Punjab,Rajasthan,Sikkim,Tamil Nadu,Telangana,Tripura,UP,Uttarakhand,West Bengal,Total Consumption
0,2013-01-06,251.5,1.6,21.3,40.9,3.8,60.3,5.8,66.0,15.0,...,95.2,192.0,1.7,254.5,127.6,2.6,225.0,33.6,107.5,2845.7
1,2013-01-07,257.9,1.7,21.2,39.6,3.8,64.3,5.8,67.2,15.1,...,92.8,192.9,1.8,262.3,129.2,2.6,219.1,34.2,106.6,2876.7
2,2013-01-08,265.1,1.6,20.4,39.2,3.9,63.0,5.9,66.7,15.2,...,93.9,197.1,1.8,256.6,131.9,2.1,238.7,33.9,103.9,2923.0
3,2013-01-09,261.0,1.6,21.4,39.5,3.7,65.0,5.8,67.4,15.2,...,90.1,197.6,1.9,254.6,135.0,2.7,229.1,32.7,105.7,2912.1
4,2013-01-10,260.0,1.6,21.1,39.7,3.8,66.5,5.9,67.8,14.9,...,93.5,199.9,1.9,255.3,130.0,3.2,224.5,35.4,105.3,2920.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,2015-05-03,135.4,1.2,19.8,56.6,4.0,76.8,6.2,81.9,16.2,...,117.5,183.7,1.1,258.6,121.6,3.0,248.0,32.4,122.3,2910.8
496,2015-05-04,142.1,1.2,19.3,55.3,4.7,76.1,6.4,86.1,16.4,...,124.1,185.0,1.1,271.4,124.4,2.9,263.4,33.7,124.1,3006.5
497,2015-05-05,142.9,1.1,19.0,55.3,4.9,79.9,6.4,92.5,16.1,...,126.6,186.1,1.4,279.9,119.0,3.2,260.7,34.5,141.9,3031.3
498,2015-05-06,144.4,1.0,21.9,59.1,5.2,79.6,6.2,95.2,16.3,...,129.6,182.8,1.4,282.2,122.3,2.3,269.9,36.2,145.8,3079.8
499,2015-05-07,142.9,1.2,20.1,60.8,5.4,79.6,6.5,97.4,16.2,...,125.8,184.1,1.2,286.6,125.8,2.8,270.1,36.9,149.2,3113.2

In [309]:
combined_df.tail(50)

,Dates,Andhra Pradesh,Arunachal Pradesh,Assam,Bihar,Chandigarh,Chhattisgarh,DD,Delhi,DNH,...,Punjab,Rajasthan,Sikkim,Tamil Nadu,Telangana,Tripura,UP,Uttarakhand,West Bengal,Total Consumption
4912,2024-08-13,226.2,3.0,45.0,148.7,7.0,121.4,NaN,121.9,NaN,...,293.8,246.7,1.0,349.3,290.6,NaN,509.0,50.1,221.5,4770.5
4913,2024-08-14,228.9,3.0,51.1,145.7,6.9,120.3,NaN,128.1,NaN,...,311.4,248.7,1.2,354.9,294.4,NaN,526.4,50.8,221.9,4867.4
4914,2024-08-15,230.9,2.9,41.0,149.1,5.7,114.2,NaN,113.0,NaN,...,292.5,230.8,0.7,313.4,287.5,NaN,553.9,43.9,209.6,4600.8
4915,2024-08-16,235.4,3.2,44.6,153.8,6.7,111.7,NaN,129.7,NaN,...,307.7,223.5,1.1,345.8,288.5,NaN,556.0,49.1,217.8,4800.6
4916,2024-08-17,227.9,3.0,48.8,162.2,6.6,114.2,NaN,132.6,NaN,...,289.7,236.5,1.2,348.5,270.8,NaN,579.1,53.0,222.5,4856.5
4917,2024-08-18,228.2,2.9,43.1,141.3,6.0,113.1,NaN,130.4,NaN,...,302.5,250.1,0.9,329.2,273.7,NaN,521.2,49.9,197.3,4691.7
4918,2024-08-19,231.2,2.9,42.0,150.3,6.6,113.4,NaN,129.0,NaN,...,292.7,249.1,1.3,350.7,263.2,NaN,532.4,40.3,202.1,4677.5
4919,2024-08-20,225.6,3.0,36.5,146.2,7.0,116.5,NaN,126.3,NaN,...,284.5,267.4,1.4,353.5,231.2,NaN,502.2,45.5,206.7,4673.4
4920,2024-08-21,227.2,3.0,40.7,150.9,7.4,120.4,NaN,129.7,NaN,...,295.0,286.8,1.3,350.2,256.6,NaN,520.5,47.3,215.3,4827.9
4921,2024-08-22,218.0,3.0,46.1,149.4,7.5,110.4,NaN,138.7,NaN,...,315.6,285.3,1.3,357.3,254.5,NaN,527.6,47.9,218.0,4867.4
4922,2024-08-23,219.1,3.3,48.4,125.2,7.5,112.2,NaN,129.7,NaN,...,316.5,279.8,1.3,369.7,257.5,NaN,521.2,49.3,201.5,4807.4
4923,2024-08-24,213.6,2.9,46.8,137.1,6.6,105.7,NaN,127.1,NaN,...,323.4,277.8,1.2,378.1,242.4,NaN,519.9,50.6,195.9,4710.9
4924,2024-08-25,214.5,2.9,46.4,145.8,6.4,103.9,NaN,121.9,NaN,...,315.0,252.8,0.7,346.6,226.0,NaN,530.1,47.6,185.4,4465.3
4925,2024-08-26,223.2,3.2,46.1,143.9,6.6,108.9,NaN,124.4,NaN,...,320.2,243.9,0.8,375.5,255.0,NaN,572.4,49.8,186.2,4570.4
4926,2024-08-27,235.1,3.2,48.2,128.9,6.6,117.2,NaN,127.2,NaN,...,238.7,238.4,1.3,386.5,283.3,NaN,537.7,52.2,191.7,4493.8
4927,2024-08-28,227.8,2.7,49.2,144.3,6.8,122.8,NaN,125.6,NaN,...,236.7,254.9,1.4,382.5,299.1,NaN,491.7,52.1,205.9,4575.5
4928,2024-08-29,228.0,3.2,50.9,149.8,6.1,119.4,NaN,118.8,NaN,...,186.3,278.8,1.2,361.3,304.9,NaN,493.5,49.2,218.1,4537.4
4929,2024-08-30,212.9,3.4,50.2,156.4,6.6,120.3,NaN,124.9,NaN,...,211.5,282.9,1.3,348.3,268.3,NaN,546.0,52.8,225.6,4631.3
4930,2024-08-31,181.9,3.0,44.1,163.7,7.0,121.9,NaN,128.6,NaN,...,249.3,282.1,1.4,338.4,223.2,NaN,576.0,54.4,224.3,4657.5
4931,2024-09-01,172.1,3.1,43.8,150.3,6.7,120.4,NaN,129.1,NaN,...,275.2,282.7,1.1,306.8,158.3,NaN,561.1,49.7,207.1,4437.8
4932,2024-09-02,186.4,3.6,46.5,155.3,7.1,123.9,NaN,133.4,NaN,...,287.8,285.0,1.3,342.4,171.3,NaN,555.7,51.7,222.1,4629.1
4933,2024-09-03,189.9,3.6,46.7,161.2,7.0,127.7,NaN,135.0,NaN,...,256.3,270.0,1.3,358.7,182.2,NaN,585.2,52.3,229.0,4663.6
4934,2024-09-04,194.1,3.2,45.0,156.3,6.3,130.8,NaN,121.3,NaN,...,234.6,238.6,1.4,367.5,187.9,NaN,540.5,48.8,227.0,4546.0
4935,2024-09-05,197.6,3.0,43.8,141.8,6.6,127.4,NaN,118.1,NaN,...,268.7,248.6,1.4,366.5,197.6,NaN,519.9,49.5,229.4,4576.2
4936,2024-09-06,201.6,3.2,49.4,147.4,6.5,125.0,NaN,121.7,NaN,...,277.1,253.5,1.4,382.7,208.9,NaN,505.5,49.9,236.3,4639.4
4937,2024-09-07,195.4,3.0,52.2,161.8,6.1,127.4,NaN,114.7,NaN,...,278.1,251.7,1.3,359.7,196.9,NaN,523.0,49.7,237.9,4565.2
4938,2024-09-08,185.7,2.9,51.2,159.7,5.8,121.9,NaN,110.2,NaN,...,284.3,252.8,1.1,319.9,190.6,NaN,525.3,46.8,218.1,4436.2
4939,2024-09-09,191.1,3.0,47.9,158.0,7.0,117.7,NaN,120.9,NaN,...,299.4,277.0,1.3,355.8,202.4,NaN,533.6,51.7,223.5,4677.0
4940,2024-09-10,201.9,3.5,50.5,156.7,6.5,96.9,NaN,123.5,NaN,...,271.1,286.9,1.4,371.1,215.9,NaN,532.9,51.5,227.6,4713.4
4941,2024-09-11,215.4,1.9,44.5,156.7,6.8,100.0,NaN,121.3,NaN,...,294.8,279.6,1.2,387.1,237.4,NaN,449.7,51.7,231.7,4664.0
4942,2024-09-12,226.7,3.1,48.5,155.0,6.8,108.3,NaN,112.5,NaN,...,310.8,271.5,1.2,387.9,256.5,NaN,374.1,45.8,238.0,4622.7
4943,2024-09-13,230.7,3.2,49.4,164.3,5.9,114.4,NaN,99.0,NaN,...,295.6,279.8,1.3,388.2,266.8,NaN,385.4,38.3,221.2,4638.9
4944,2024-09-14,230.3,4.4,49.0,130.2,5.4,116.1,NaN,96.9,NaN,...,309.6,287.5,1.3,397.0,270.0,NaN,426.9,40.3,168.6,4618.0
4945,2024-09-15,230.9,3.2,46.7,125.7,4.7,119.2,NaN,99.6,NaN,...,306.8,287.3,1.0,362.2,274.3,NaN,446.5,40.0,143.8,4509.0
4946,2024-09-16,238.4,3.0,47.7,106.3,5.6,116.6,NaN,107.1,NaN,...,312.6,296.2,1.2,389.5,286.7,NaN,463.7,46.0,152.3,4680.7
4947,2024-09-17,242.6,3.2,49.6,117.2,6.1,101.5,NaN,114.2,NaN,...,310.8,303.2,1.3,405.3,289.5,NaN,416.5,44.1,167.9,4674.4
4948,2024-09-18,245.0,4.6,51.3,138.3,6.0,109.8,NaN,107.8,NaN,...,296.8,300.5,1.3,406.1,296.5,NaN,377.9,45.4,195.0,4745.1
4949,2024-09-19,246.1,3.4,54.5,149.3,5.9,121.2,NaN,103.0,NaN,...,266.6,299.2,1.3,403.1,303.8,NaN,421.8,45.7,222.2,4894.7
4950,2024-09-20,242.6,3.6,55.8,159.5,6.2,130.8,NaN,111.2,NaN,...,264.4,297.5,1.5,408.0,299.5,NaN,464.1,49.3,238.6,5051.5
4951,2024-09-21,231.9,3.4,55.1,159.9,6.4,131.8,NaN,115.1,NaN,...,296.8,317.7,1.3,381.8,251.3,NaN,492.9,51.2,232.0,5053.2
4952,2024-09-22,225.8,3.5,52.2,163.5,6.2,125.1,NaN,117.8,NaN,...,300.3,325.9,1.0,354.6,231.8,NaN,508.7,48.5,227.9,4924.4
4953,2024-09-23,223.9,4.4,52.2,165.6,7.4,126.1,NaN,131.3,NaN,...,298.1,329.2,1.5,381.4,243.2,NaN,543.4,50.4,243.0,5102.3
4954,2024-09-24,217.3,2.5,45.6,149.9,7.9,119.6,NaN,139.0,NaN,...,321.4,344.8,1.4,380.8,225.4,NaN,571.0,53.6,222.9,5100.4
4955,2024-09-25,204.9,2.5,45.1,131.7,7.4,117.1,NaN,140.0,NaN,...,340.1,354.8,1.4,384.0,213.8,NaN,542.3,51.6,195.8,4969.5
4956,2024-09-26,205.6,2.6,36.0,108.9,6.3,111.9,NaN,133.6,NaN,...,320.6,347.1,1.4,388.9,213.6,NaN,486.9,50.1,178.0,4744.7
4957,2024-09-27,208.6,2.6,40.1,96.3,5.7,107.1,NaN,129.6,NaN,...,281.4,341.1,1.2,389.8,229.6,NaN,400.8,48.6,181.1,4589.9
4958,2024-09-28,212.9,2.8,38.5,100.9,5.3,109.9,NaN,116.9,NaN,...,248.0,324.1,1.1,390.9,247.8,NaN,383.8,47.2,195.9,4510.7
4959,2024-09-29,212.7,2.8,37.8,118.0,5.1,116.5,NaN,113.4,NaN,...,245.2,318.2,1.0,352.2,258.4,NaN,399.8,44.1,203.9,4457.8
4960,22-03-2020_x,176.7,2.1,19.0,68.2,2.4,81.6,3.6,46.1,13.5,...,86.3,178.7,1.0,276.5,219.7,NaN,240.8,22.5,100.4,3022.3
4961,22-03-2020_y,176.7,2.1,19.0,68.2,2.4,81.6,3.6,46.1,13.5,...,86.3,178.7,1.0,276.5,219.7,NaN,240.8,22.5,100.4,3022.3

In [310]:
combined_df.drop([4960,4961], inplace=True)

In [311]:
combined_df.to_csv('/Users/aryankhurana/Electricity-Forecasting-Indian-States/Electricity_Consumption_Dataset.csv', index=False)

In [296]:
elec_data = pd.read_csv('/Users/aryankhurana/Electricity-Forecasting-Indian-States/Electricity_Consumption_Dataset.csv')
elec_data.head(50)

,Dates,Andhra Pradesh,Arunachal Pradesh,Assam,Bihar,Chandigarh,Chhattisgarh,DD,DNH,DVC,...,Rajasthan,Sikkim,Tamil Nadu,Telangana,Tripura,UP,Uttarakhand,West Bengal,Total Consumption,Pondy
0,2013-01-06,251.5,1.6,21.3,40.9,3.8,60.3,5.8,15.0,56.2,...,192.0,1.7,254.5,127.6,2.6,225.0,33.6,107.5,NaN,5.6
1,2013-01-07,257.9,1.7,21.2,39.6,3.8,64.3,5.8,15.1,59.9,...,192.9,1.8,262.3,129.2,2.6,219.1,34.2,106.6,NaN,5.5
2,2013-01-08,265.1,1.6,20.4,39.2,3.9,63.0,5.9,15.2,60.3,...,197.1,1.8,256.6,131.9,2.1,238.7,33.9,103.9,NaN,5.8
3,2013-01-09,261.0,1.6,21.4,39.5,3.7,65.0,5.8,15.2,60.0,...,197.6,1.9,254.6,135.0,2.7,229.1,32.7,105.7,NaN,5.9
4,2013-01-10,260.0,1.6,21.1,39.7,3.8,66.5,5.9,14.9,58.9,...,199.9,1.9,255.3,130.0,3.2,224.5,35.4,105.3,NaN,5.9
5,2013-01-11,254.5,1.5,20.9,34.3,3.6,64.3,5.8,14.7,57.5,...,197.5,2.0,256.3,132.0,2.7,222.9,33.4,107.4,NaN,5.9
6,2013-01-12,257.4,1.6,20.2,39.9,3.4,65.1,5.8,14.8,55.6,...,195.4,1.5,248.8,130.9,3.0,222.6,32.4,97.8,NaN,5.8
7,2013-07-15,221.1,1.2,24.8,45.0,5.9,63.8,6.0,13.3,61.2,...,142.8,1.3,250.4,118.6,3.0,242.5,35.0,135.7,NaN,6.2
8,2013-07-16,221.3,1.1,24.7,43.5,5.7,63.9,6.2,14.4,61.2,...,146.3,1.3,249.2,115.9,3.0,246.6,34.2,135.7,NaN,6.1
9,2013-07-17,211.8,1.3,25.4,43.9,6.0,65.2,5.9,14.2,61.2,...,152.0,1.3,251.6,124.7,3.0,248.8,33.4,135.7,NaN,6.0
10,2013-07-18,214.6,1.3,24.7,44.5,5.7,66.9,6.1,14.2,61.2,...,146.9,1.3,251.6,123.4,3.2,253.7,33.1,135.7,NaN,6.2
11,2013-07-19,206.3,1.1,24.6,43.2,5.9,68.5,6.1,13.7,61.2,...,150.4,1.3,245.1,123.7,3.0,246.6,33.8,135.7,NaN,6.2
12,2013-07-20,207.2,1.1,24.6,44.0,5.1,64.9,6.1,12.4,61.2,...,143.4,1.3,238.8,125.8,2.5,236.1,34.5,135.7,NaN,6.0
13,2013-07-21,213.4,1.2,24.6,44.5,4.9,62.7,5.9,12.5,61.2,...,132.8,1.3,228.5,125.8,2.5,236.3,31.0,135.7,NaN,5.6
14,2013-07-22,209.9,1.2,23.2,38.9,5.6,63.3,5.8,12.2,58.5,...,133.2,0.9,243.0,121.3,2.9,241.6,32.1,135.9,NaN,5.9
15,2013-07-23,202.0,1.3,23.0,40.2,5.9,63.0,5.9,12.6,58.9,...,137.4,1.0,246.8,121.0,2.7,245.0,31.4,135.2,NaN,6.0
16,2013-07-24,213.7,0.7,25.4,41.4,6.0,61.8,5.9,12.6,60.0,...,145.0,1.2,247.9,123.6,3.1,243.1,28.4,137.8,NaN,6.2
17,2013-07-25,226.4,0.7,25.6,40.2,6.0,62.7,6.1,12.6,57.4,...,142.8,1.2,242.3,127.2,2.9,242.1,27.8,134.8,NaN,6.2
18,2013-07-26,233.8,0.8,21.2,38.5,5.9,60.6,6.1,13.9,58.0,...,135.4,1.3,253.0,125.9,2.7,240.9,32.7,131.2,NaN,6.4
19,2013-07-27,236.8,1.3,25.1,36.9,5.9,56.6,6.0,12.9,57.6,...,129.1,1.0,252.4,130.9,2.3,245.2,33.3,117.5,NaN,6.7
20,2013-07-28,235.9,1.4,24.7,39.8,5.6,59.1,6.0,14.0,56.3,...,125.9,1.0,246.1,127.0,2.3,242.5,32.6,123.6,NaN,6.2
21,2013-07-29,243.6,1.1,24.8,40.0,7.3,59.9,6.0,13.7,57.6,...,132.3,1.1,254.8,122.1,2.3,247.9,32.7,117.5,NaN,6.5
22,2013-07-30,238.0,1.2,24.9,41.1,5.2,55.7,6.0,14.4,55.7,...,132.2,1.3,261.6,119.5,2.8,246.0,31.9,126.4,NaN,6.5
23,2013-07-31,220.2,1.1,24.4,41.7,6.3,55.5,5.9,14.8,55.4,...,135.9,1.3,258.5,118.5,2.5,250.9,28.9,127.8,NaN,6.5
24,2013-08-01,223.3,1.2,25.8,41.1,6.3,58.2,5.9,14.4,54.5,...,135.4,1.2,257.4,124.2,2.8,246.5,27.8,128.9,NaN,6.6
25,2013-08-02,234.8,1.1,25.9,45.0,5.8,57.0,6.0,14.3,57.2,...,149.1,1.2,260.1,121.9,2.8,252.9,33.4,129.5,NaN,6.7
26,2013-08-03,247.8,1.2,26.0,43.7,5.7,56.8,6.0,14.2,57.9,...,150.9,0.6,252.9,118.4,2.9,256.7,33.3,133.0,NaN,6.6
27,2013-08-04,247.7,1.0,24.9,40.2,5.3,58.5,6.0,14.9,56.5,...,148.7,0.8,238.4,122.2,2.8,259.1,31.4,129.2,NaN,6.3
28,2013-08-12,235.1,1.1,24.8,41.7,5.6,61.1,6.1,15.2,57.5,...,137.6,1.2,229.6,146.0,3.0,236.1,32.1,124.0,NaN,5.9
29,2013-08-13,241.7,1.2,24.7,43.4,5.3,64.9,6.1,15.2,61.0,...,135.4,1.1,233.7,134.7,3.2,237.8,28.7,137.5,NaN,5.4
30,2013-08-14,248.1,1.7,24.6,43.3,5.5,67.1,6.2,15.1,59.3,...,129.7,1.3,237.9,141.1,3.1,237.1,32.0,135.0,NaN,5.6
31,2013-08-16,222.7,1.3,22.1,40.4,5.1,61.0,5.5,14.0,56.8,...,117.2,1.9,228.4,135.5,2.6,229.2,33.1,128.6,NaN,4.6
32,2013-08-17,221.5,1.3,25.3,41.5,4.8,60.2,5.5,15.0,56.6,...,117.7,0.9,225.3,136.8,3.0,225.2,34.0,128.3,NaN,5.0
33,2013-08-18,220.6,1.6,23.5,41.7,4.5,55.1,6.3,15.4,55.5,...,120.3,0.9,219.7,136.9,2.5,226.9,33.0,121.2,NaN,6.4
34,2013-08-19,230.4,1.2,23.7,42.2,5.0,58.7,6.3,15.0,58.3,...,129.0,1.0,223.3,140.0,2.9,227.0,33.5,120.6,NaN,5.8
35,2013-08-20,237.9,1.4,24.4,42.0,5.1,54.2,5.2,14.6,56.4,...,117.4,0.9,243.5,134.4,3.3,225.6,31.8,106.4,NaN,6.1
36,2013-08-21,244.6,1.2,24.9,31.9,5.4,55.3,5.8,15.0,52.1,...,123.5,1.0,246.5,128.0,2.8,224.2,30.1,101.6,NaN,6.2
37,2013-08-22,246.4,1.1,22.9,36.5,5.4,55.9,6.4,14.7,53.5,...,129.6,1.0,250.7,132.6,3.3,225.6,32.0,117.0,NaN,6.3
38,2013-08-23,263.2,1.3,23.4,41.0,5.4,58.6,5.7,15.1,58.5,...,143.6,1.1,253.6,138.4,3.4,227.1,34.8,124.5,NaN,6.3
39,2013-08-24,221.5,1.3,19.6,41.5,4.8,60.2,5.5,15.0,56.6,...,117.7,0.9,225.3,136.9,4.3,225.2,34.0,128.3,NaN,5.0
40,2013-08-27,264.2,1.1,21.7,38.3,5.9,62.3,6.2,15.2,58.7,...,161.6,0.9,245.3,140.5,3.4,236.4,32.8,129.3,NaN,5.7
41,2013-08-28,265.3,1.2,22.3,38.3,5.0,47.5,6.3,15.2,57.9,...,162.4,1.1,243.0,136.8,3.7,237.8,31.1,123.5,NaN,6.7
42,2013-08-29,264.1,1.2,22.7,39.2,5.4,55.9,6.3,15.2,56.0,...,157.9,1.1,227.5,127.9,3.5,227.9,31.9,124.2,NaN,6.2
43,2013-08-31,261.0,1.4,22.0,39.8,5.1,61.2,6.3,15.2,56.2,...,165.9,1.2,226.3,116.5,3.6,212.9,31.1,131.1,NaN,6.6
44,2013-09-01,253.2,1.3,22.0,36.4,4.7,61.8,6.0,15.2,55.6,...,169.3,1.0,227.6,118.8,3.4,205.1,28.1,120.6,NaN,6.2
45,2013-09-02,255.4,1.2,23.8,38.0,5.6,64.7,6.1,15.3,56.7,...,174.1,1.1,231.1,123.0,3.4,217.1,32.6,121.3,NaN,6.4
46,2013-09-03,254.8,1.3,24.4,37.8,5.7,64.5,6.3,15.4,56.1,...,175.7,1.1,241.9,127.0,3.6,219.5,32.5,126.7,NaN,6.6
47,2013-09-04,255.5,1.2,24.2,38.3,5.7,64.4,6.3,15.4,55.8,...,176.2,1.2,240.7,139.3,3.6,221.2,31.5,127.1,NaN,6.5
48,2013-09-05,260.5,1.2,23.6,40.5,5.6,62.5,6.5,15.4,55.3,...,175.2,1.2,254.9,145.9,3.1,227.6,32.5,136.8,NaN,6.3
49,2013-09-06,262.9,1.3,23.3,42.9,5.1,67.8,5.7,15.3,58.8,...,172.1,1.1,248.6,149.6,2.8,233.9,32.5,131.0,NaN,5.8

In [295]:
elec_data['Total Consumption'] = elec_data.iloc[:, 1:].sum(axis=1)
elec_data.head(50)

,Dates,Andhra Pradesh,Arunachal Pradesh,Assam,Bihar,Chandigarh,Chhattisgarh,DD,DNH,DVC,...,Rajasthan,Sikkim,Tamil Nadu,Telangana,Tripura,UP,Uttarakhand,West Bengal,Total Consumption,Pondy
0,2013-01-06,251.5,1.6,21.3,40.9,3.8,60.3,5.8,15.0,56.2,...,192.0,1.7,254.5,127.6,2.6,225.0,33.6,107.5,8537.1,5.6
1,2013-01-07,257.9,1.7,21.2,39.6,3.8,64.3,5.8,15.1,59.9,...,192.9,1.8,262.3,129.2,2.6,219.1,34.2,106.6,8630.1,5.5
2,2013-01-08,265.1,1.6,20.4,39.2,3.9,63.0,5.9,15.2,60.3,...,197.1,1.8,256.6,131.9,2.1,238.7,33.9,103.9,8769.0,5.8
3,2013-01-09,261.0,1.6,21.4,39.5,3.7,65.0,5.8,15.2,60.0,...,197.6,1.9,254.6,135.0,2.7,229.1,32.7,105.7,8736.3,5.9
4,2013-01-10,260.0,1.6,21.1,39.7,3.8,66.5,5.9,14.9,58.9,...,199.9,1.9,255.3,130.0,3.2,224.5,35.4,105.3,8762.4,5.9
5,2013-01-11,254.5,1.5,20.9,34.3,3.6,64.3,5.8,14.7,57.5,...,197.5,2.0,256.3,132.0,2.7,222.9,33.4,107.4,8648.7,5.9
6,2013-01-12,257.4,1.6,20.2,39.9,3.4,65.1,5.8,14.8,55.6,...,195.4,1.5,248.8,130.9,3.0,222.6,32.4,97.8,8514.9,5.8
7,2013-07-15,221.1,1.2,24.8,45.0,5.9,63.8,6.0,13.3,61.2,...,142.8,1.3,250.4,118.6,3.0,242.5,35.0,135.7,8461.5,6.2
8,2013-07-16,221.3,1.1,24.7,43.5,5.7,63.9,6.2,14.4,61.2,...,146.3,1.3,249.2,115.9,3.0,246.6,34.2,135.7,8494.2,6.1
9,2013-07-17,211.8,1.3,25.4,43.9,6.0,65.2,5.9,14.2,61.2,...,152.0,1.3,251.6,124.7,3.0,248.8,33.4,135.7,8567.1,6.0
10,2013-07-18,214.6,1.3,24.7,44.5,5.7,66.9,6.1,14.2,61.2,...,146.9,1.3,251.6,123.4,3.2,253.7,33.1,135.7,8551.2,6.2
11,2013-07-19,206.3,1.1,24.6,43.2,5.9,68.5,6.1,13.7,61.2,...,150.4,1.3,245.1,123.7,3.0,246.6,33.8,135.7,8472.9,6.2
12,2013-07-20,207.2,1.1,24.6,44.0,5.1,64.9,6.1,12.4,61.2,...,143.4,1.3,238.8,125.8,2.5,236.1,34.5,135.7,8209.8,6.0
13,2013-07-21,213.4,1.2,24.6,44.5,4.9,62.7,5.9,12.5,61.2,...,132.8,1.3,228.5,125.8,2.5,236.3,31.0,135.7,8052.3,5.6
14,2013-07-22,209.9,1.2,23.2,38.9,5.6,63.3,5.8,12.2,58.5,...,133.2,0.9,243.0,121.3,2.9,241.6,32.1,135.9,8307.0,5.9
15,2013-07-23,202.0,1.3,23.0,40.2,5.9,63.0,5.9,12.6,58.9,...,137.4,1.0,246.8,121.0,2.7,245.0,31.4,135.2,8212.2,6.0
16,2013-07-24,213.7,0.7,25.4,41.4,6.0,61.8,5.9,12.6,60.0,...,145.0,1.2,247.9,123.6,3.1,243.1,28.4,137.8,8305.2,6.2
17,2013-07-25,226.4,0.7,25.6,40.2,6.0,62.7,6.1,12.6,57.4,...,142.8,1.2,242.3,127.2,2.9,242.1,27.8,134.8,8286.0,6.2
18,2013-07-26,233.8,0.8,21.2,38.5,5.9,60.6,6.1,13.9,58.0,...,135.4,1.3,253.0,125.9,2.7,240.9,32.7,131.2,8283.3,6.4
19,2013-07-27,236.8,1.3,25.1,36.9,5.9,56.6,6.0,12.9,57.6,...,129.1,1.0,252.4,130.9,2.3,245.2,33.3,117.5,8243.1,6.7
20,2013-07-28,235.9,1.4,24.7,39.8,5.6,59.1,6.0,14.0,56.3,...,125.9,1.0,246.1,127.0,2.3,242.5,32.6,123.6,8122.8,6.2
21,2013-07-29,243.6,1.1,24.8,40.0,7.3,59.9,6.0,13.7,57.6,...,132.3,1.1,254.8,122.1,2.3,247.9,32.7,117.5,8335.5,6.5
22,2013-07-30,238.0,1.2,24.9,41.1,5.2,55.7,6.0,14.4,55.7,...,132.2,1.3,261.6,119.5,2.8,246.0,31.9,126.4,8342.4,6.5
23,2013-07-31,220.2,1.1,24.4,41.7,6.3,55.5,5.9,14.8,55.4,...,135.9,1.3,258.5,118.5,2.5,250.9,28.9,127.8,8286.6,6.5
24,2013-08-01,223.3,1.2,25.8,41.1,6.3,58.2,5.9,14.4,54.5,...,135.4,1.2,257.4,124.2,2.8,246.5,27.8,128.9,8186.4,6.6
25,2013-08-02,234.8,1.1,25.9,45.0,5.8,57.0,6.0,14.3,57.2,...,149.1,1.2,260.1,121.9,2.8,252.9,33.4,129.5,8316.3,6.7
26,2013-08-03,247.8,1.2,26.0,43.7,5.7,56.8,6.0,14.2,57.9,...,150.9,0.6,252.9,118.4,2.9,256.7,33.3,133.0,8424.9,6.6
27,2013-08-04,247.7,1.0,24.9,40.2,5.3,58.5,6.0,14.9,56.5,...,148.7,0.8,238.4,122.2,2.8,259.1,31.4,129.2,8272.5,6.3
28,2013-08-12,235.1,1.1,24.8,41.7,5.6,61.1,6.1,15.2,57.5,...,137.6,1.2,229.6,146.0,3.0,236.1,32.1,124.0,8370.9,5.9
29,2013-08-13,241.7,1.2,24.7,43.4,5.3,64.9,6.1,15.2,61.0,...,135.4,1.1,233.7,134.7,3.2,237.8,28.7,137.5,8381.7,5.4
30,2013-08-14,248.1,1.7,24.6,43.3,5.5,67.1,6.2,15.1,59.3,...,129.7,1.3,237.9,141.1,3.1,237.1,32.0,135.0,8403.3,5.6
31,2013-08-16,222.7,1.3,22.1,40.4,5.1,61.0,5.5,14.0,56.8,...,117.2,1.9,228.4,135.5,2.6,229.2,33.1,128.6,7840.8,4.6
32,2013-08-17,221.5,1.3,25.3,41.5,4.8,60.2,5.5,15.0,56.6,...,117.7,0.9,225.3,136.8,3.0,225.2,34.0,128.3,7866.9,5.0
33,2013-08-18,220.6,1.6,23.5,41.7,4.5,55.1,6.3,15.4,55.5,...,120.3,0.9,219.7,136.9,2.5,226.9,33.0,121.2,7735.8,6.4
34,2013-08-19,230.4,1.2,23.7,42.2,5.0,58.7,6.3,15.0,58.3,...,129.0,1.0,223.3,140.0,2.9,227.0,33.5,120.6,7959.9,5.8
35,2013-08-20,237.9,1.4,24.4,42.0,5.1,54.2,5.2,14.6,56.4,...,117.4,0.9,243.5,134.4,3.3,225.6,31.8,106.4,7865.7,6.1
36,2013-08-21,244.6,1.2,24.9,31.9,5.4,55.3,5.8,15.0,52.1,...,123.5,1.0,246.5,128.0,2.8,224.2,30.1,101.6,7955.1,6.2
37,2013-08-22,246.4,1.1,22.9,36.5,5.4,55.9,6.4,14.7,53.5,...,129.6,1.0,250.7,132.6,3.3,225.6,32.0,117.0,8180.4,6.3
38,2013-08-23,263.2,1.3,23.4,41.0,5.4,58.6,5.7,15.1,58.5,...,143.6,1.1,253.6,138.4,3.4,227.1,34.8,124.5,8507.4,6.3
39,2013-08-24,221.5,1.3,19.6,41.5,4.8,60.2,5.5,15.0,56.6,...,117.7,0.9,225.3,136.9,4.3,225.2,34.0,128.3,7854.0,5.0
40,2013-08-27,264.2,1.1,21.7,38.3,5.9,62.3,6.2,15.2,58.7,...,161.6,0.9,245.3,140.5,3.4,236.4,32.8,129.3,8803.5,5.7
41,2013-08-28,265.3,1.2,22.3,38.3,5.0,47.5,6.3,15.2,57.9,...,162.4,1.1,243.0,136.8,3.7,237.8,31.1,123.5,8679.6,6.7
42,2013-08-29,264.1,1.2,22.7,39.2,5.4,55.9,6.3,15.2,56.0,...,157.9,1.1,227.5,127.9,3.5,227.9,31.9,124.2,8658.3,6.2
43,2013-08-31,261.0,1.4,22.0,39.8,5.1,61.2,6.3,15.2,56.2,...,165.9,1.2,226.3,116.5,3.6,212.9,31.1,131.1,8710.2,6.6
44,2013-09-01,253.2,1.3,22.0,36.4,4.7,61.8,6.0,15.2,55.6,...,169.3,1.0,227.6,118.8,3.4,205.1,28.1,120.6,8499.9,6.2
45,2013-09-02,255.4,1.2,23.8,38.0,5.6,64.7,6.1,15.3,56.7,...,174.1,1.1,231.1,123.0,3.4,217.1,32.6,121.3,8797.8,6.4
46,2013-09-03,254.8,1.3,24.4,37.8,5.7,64.5,6.3,15.4,56.1,...,175.7,1.1,241.9,127.0,3.6,219.5,32.5,126.7,8907.9,6.6
47,2013-09-04,255.5,1.2,24.2,38.3,5.7,64.4,6.3,15.4,55.8,...,176.2,1.2,240.7,139.3,3.6,221.2,31.5,127.1,8992.5,6.5
48,2013-09-05,260.5,1.2,23.6,40.5,5.6,62.5,6.5,15.4,55.3,...,175.2,1.2,254.9,145.9,3.1,227.6,32.5,136.8,9120.9,6.3
49,2013-09-06,262.9,1.3,23.3,42.9,5.1,67.8,5.7,15.3,58.8,...,172.1,1.1,248.6,149.6,2.8,233.9,32.5,131.0,9115.8,5.8

In [ ]:
elec_data = elec_data.sort_values('Dates')
elec_data = elec_data.reset_index(drop=True)
elec_data.head(50)